In [9]:
# llm_list = ['gemma2','llama3.1']
# for llm_model in llm_list:
#   !ollama pull {llm_model}

pulling manifest ⠋ pulling manifest ⠙ pulling manifest ⠹ pulling manifest ⠸ pulling manifest ⠼ pulling manifest ⠴ pulling manifest ⠦ pulling manifest ⠧ pulling manifest ⠇ pulling manifest ⠏ pulling manifest ⠋ pulling manifest ⠙ pulling manifest ⠹ pulling manifest ⠸ pulling manifest ⠼ pulling manifest ⠴ pulling manifest
pulling ff1d1fc78170... 100% ▕████████████████▏ 5.4 GB
pulling 109037bec39c... 100% ▕████████████████▏  136 B
pulling 097a36493f71... 100% ▕████████████████▏ 8.4 KB
pulling 2490e7468436... 100% ▕████████████████▏   65 B
pulling 10aa81da732e... 100% ▕████████████████▏  487 B
verifying sha256 digest
writing manifest
success
pulling manifest ⠋ pulling manifest ⠙ pulling manifest ⠹ pulling manifest ⠸ pulling manifest ⠼ pulling manifest ⠴ pulling manifest ⠦ pulling manifest ⠧ pulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 666 MB/4.9 GB                  pulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 666 MB/4.9 GB                  pulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 666 MB/4.9 GB                  pulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 667 MB/4.9 GB                  pulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 667 MB/4.9 GB                  pulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 668 MB/4.9 GB                  pulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 668 MB/4.9 GB                  pulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 669 MB/4.9 GB                  pulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 669 MB/4.9 GB                  pulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 669 MB/4.9 GB                  pulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 670 MB/4.9 GB  4.4 MB/s   16m9spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 671 MB/4.9 GB  4.4 MB/s   16m9spulling manifest

pulling 667b0c1932bc...  14% ▕██              ▏ 671 MB/4.9 GB  4.4 MB/s   16m9spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 671 MB/4.9 GB  4.4 MB/s   16m9spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 672 MB/4.9 GB  4.4 MB/s   16m9spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 672 MB/4.9 GB  4.4 MB/s   16m9spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 673 MB/4.9 GB  4.4 MB/s   16m9spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 673 MB/4.9 GB  4.4 MB/s   16m9spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 674 MB/4.9 GB  4.4 MB/s   16m8spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 674 MB/4.9 GB  4.4 MB/s   16m8spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 675 MB/4.9 GB  4.7 MB/s  14m59spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 676 MB/4.9 GB  4.7 MB/s  14m59spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 676 MB/4.9 GB  4.7 MB/s  14m59spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 676 MB/4.9 GB  4.7 MB/s  14m58spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 677 MB/4.9 GB  4.7 MB/s  14m58spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 678 MB/4.9 GB  4.7 MB/s  14m58spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 678 MB/4.9 GB  4.7 MB/s  14m58spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 678 MB/4.9 GB  4.7 MB/s  14m58spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 679 MB/4.9 GB  4.7 MB/s  14m58spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 679 MB/4.9 GB  4.7 MB/s  14m58spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 680 MB/4.9 GB  4.7 MB/s   15m3spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 680 MB/4.9 GB  4.7 MB/s   15m3spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 680 MB/4.9 GB  4.7 MB/s   15m3spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 681 MB/4.9 GB  4.7 MB/s   15m3spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 682 MB/4.9 GB  4.7 MB/s   15m3spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 682 MB/4.9 GB  4.7 MB/s   15m3spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 682 MB/4.9 GB  4.7 MB/s   15m3spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 683 MB/4.9 GB  4.7 MB/s   15m2spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 683 MB/4.9 GB  4.7 MB/s   15m2spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 683 MB/4.9 GB  4.7 MB/s   15m2spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 683 MB/4.9 GB  4.5 MB/s  15m51spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 684 MB/4.9 GB  4.5 MB/s  15m51spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 684 MB/4.9 GB  4.5 MB/s  15m51spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 685 MB/4.9 GB  4.5 MB/s  15m50spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 686 MB/4.9 GB  4.5 MB/s  15m50spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 686 MB/4.9 GB  4.5 MB/s  15m50spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 687 MB/4.9 GB  4.5 MB/s  15m50spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 687 MB/4.9 GB  4.5 MB/s  15m50spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 688 MB/4.9 GB  4.5 MB/s  15m50spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 688 MB/4.9 GB  4.5 MB/s  15m50spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 689 MB/4.9 GB  4.5 MB/s  15m50spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 689 MB/4.9 GB  4.6 MB/s  15m11spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 689 MB/4.9 GB  4.6 MB/s  15m11spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 690 MB/4.9 GB  4.6 MB/s  15m11spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 690 MB/4.9 GB  4.6 MB/s  15m11spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 691 MB/4.9 GB  4.6 MB/s  15m11spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 691 MB/4.9 GB  4.6 MB/s  15m11spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 692 MB/4.9 GB  4.6 MB/s  15m11spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 692 MB/4.9 GB  4.6 MB/s  15m11spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 692 MB/4.9 GB  4.6 MB/s  15m11spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 693 MB/4.9 GB  4.6 MB/s  15m11spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 693 MB/4.9 GB  4.6 MB/s  15m26spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 693 MB/4.9 GB  4.6 MB/s  15m26spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 693 MB/4.9 GB  4.6 MB/s  15m26spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 694 MB/4.9 GB  4.6 MB/s  15m26spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 695 MB/4.9 GB  4.6 MB/s  15m25spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 695 MB/4.9 GB  4.6 MB/s  15m25spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 695 MB/4.9 GB  4.6 MB/s  15m25spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 696 MB/4.9 GB  4.6 MB/s  15m25spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 696 MB/4.9 GB  4.6 MB/s  15m25spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 697 MB/4.9 GB  4.6 MB/s  15m25spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 697 MB/4.9 GB  4.6 MB/s  15m25spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 697 MB/4.9 GB  4.5 MB/s  15m36spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 697 MB/4.9 GB  4.5 MB/s  15m36spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 698 MB/4.9 GB  4.5 MB/s  15m35spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 698 MB/4.9 GB  4.5 MB/s  15m35spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 699 MB/4.9 GB  4.5 MB/s  15m35spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 699 MB/4.9 GB  4.5 MB/s  15m35spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 699 MB/4.9 GB  4.5 MB/s  15m35spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 700 MB/4.9 GB  4.5 MB/s  15m35spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 700 MB/4.9 GB  4.5 MB/s  15m35spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 700 MB/4.9 GB  4.5 MB/s  15m35spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 701 MB/4.9 GB  4.4 MB/s  15m55spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 701 MB/4.9 GB  4.4 MB/s  15m55spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 701 MB/4.9 GB  4.4 MB/s  15m55spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 702 MB/4.9 GB  4.4 MB/s  15m55spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 702 MB/4.9 GB  4.4 MB/s  15m55spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 702 MB/4.9 GB  4.4 MB/s  15m55spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 703 MB/4.9 GB  4.4 MB/s  15m55spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 703 MB/4.9 GB  4.4 MB/s  15m54spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 704 MB/4.9 GB  4.4 MB/s  15m54spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 704 MB/4.9 GB  4.4 MB/s  15m54spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 704 MB/4.9 GB  4.4 MB/s  15m54spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 705 MB/4.9 GB  4.3 MB/s  16m10spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 705 MB/4.9 GB  4.3 MB/s  16m10spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 706 MB/4.9 GB  4.3 MB/s   16m9spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 706 MB/4.9 GB  4.3 MB/s   16m9spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 706 MB/4.9 GB  4.3 MB/s   16m9spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 707 MB/4.9 GB  4.3 MB/s   16m9spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 707 MB/4.9 GB  4.3 MB/s   16m9spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 708 MB/4.9 GB  4.3 MB/s   16m9spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 708 MB/4.9 GB  4.3 MB/s   16m9spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 709 MB/4.9 GB  4.3 MB/s   16m9spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 709 MB/4.9 GB  4.3 MB/s   16m9spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 709 MB/4.9 GB  4.4 MB/s   16m7spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 710 MB/4.9 GB  4.4 MB/s   16m7spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 710 MB/4.9 GB  4.4 MB/s   16m7spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 711 MB/4.9 GB  4.4 MB/s   16m7spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 711 MB/4.9 GB  4.4 MB/s   16m6spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 712 MB/4.9 GB  4.4 MB/s   16m6spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 712 MB/4.9 GB  4.4 MB/s   16m6spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 712 MB/4.9 GB  4.4 MB/s   16m6spulling manifest
pulling 667b0c1932bc...  14% ▕██              ▏ 713 MB/4.9 GB  4.4 MB/s   16m6spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 713 MB/4.9 GB  4.4 MB/s   16m6spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 714 MB/4.9 GB  4.3 MB/s  16m20spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 714 MB/4.9 GB  4.3 MB/s  16m20spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 715 MB/4.9 GB  4.3 MB/s  16m19spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 715 MB/4.9 GB  4.3 MB/s  16m19spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 715 MB/4.9 GB  4.3 MB/s  16m19spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 716 MB/4.9 GB  4.3 MB/s  16m19spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 716 MB/4.9 GB  4.3 MB/s  16m19spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 716 MB/4.9 GB  4.3 MB/s  16m19spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 717 MB/4.9 GB  4.3 MB/s  16m19spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 717 MB/4.9 GB  4.3 MB/s  16m19spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 717 MB/4.9 GB  4.3 MB/s  16m19spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 718 MB/4.9 GB  4.2 MB/s  16m36spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 718 MB/4.9 GB  4.2 MB/s  16m35spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 719 MB/4.9 GB  4.2 MB/s  16m35spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 719 MB/4.9 GB  4.2 MB/s  16m35spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 720 MB/4.9 GB  4.2 MB/s  16m35spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 720 MB/4.9 GB  4.2 MB/s  16m35spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 720 MB/4.9 GB  4.2 MB/s  16m35spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 721 MB/4.9 GB  4.2 MB/s  16m35spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 721 MB/4.9 GB  4.2 MB/s  16m35spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 722 MB/4.9 GB  4.2 MB/s  16m35spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 722 MB/4.9 GB  4.3 MB/s  16m20spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 722 MB/4.9 GB  4.3 MB/s  16m20spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 723 MB/4.9 GB  4.3 MB/s  16m19spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 723 MB/4.9 GB  4.3 MB/s  16m19spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 724 MB/4.9 GB  4.3 MB/s  16m19spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 724 MB/4.9 GB  4.3 MB/s  16m19spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 724 MB/4.9 GB  4.3 MB/s  16m19spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 724 MB/4.9 GB  4.3 MB/s  16m19spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 724 MB/4.9 GB  4.3 MB/s  16m19spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 725 MB/4.9 GB  4.3 MB/s  16m19spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 725 MB/4.9 GB  4.0 MB/s  17m17spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 725 MB/4.9 GB  4.0 MB/s  17m17spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 726 MB/4.9 GB  4.0 MB/s  17m17spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 726 MB/4.9 GB  4.0 MB/s  17m17spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 726 MB/4.9 GB  4.0 MB/s  17m17spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 726 MB/4.9 GB  4.0 MB/s  17m17spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 727 MB/4.9 GB  4.0 MB/s  17m17spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 727 MB/4.9 GB  4.0 MB/s  17m17spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 727 MB/4.9 GB  4.0 MB/s  17m17spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 728 MB/4.9 GB  4.0 MB/s  17m17spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 728 MB/4.9 GB  4.0 MB/s  17m17spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 729 MB/4.9 GB  4.0 MB/s  17m37spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 729 MB/4.9 GB  4.0 MB/s  17m37spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 730 MB/4.9 GB  4.0 MB/s  17m37spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 730 MB/4.9 GB  4.0 MB/s  17m37spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 731 MB/4.9 GB  4.0 MB/s  17m37spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 731 MB/4.9 GB  4.0 MB/s  17m37spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 731 MB/4.9 GB  4.0 MB/s  17m36spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 732 MB/4.9 GB  4.0 MB/s  17m36spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 732 MB/4.9 GB  4.0 MB/s  17m36spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 733 MB/4.9 GB  4.0 MB/s  17m36spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 733 MB/4.9 GB  4.0 MB/s  17m22spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 734 MB/4.9 GB  4.0 MB/s  17m22spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 734 MB/4.9 GB  4.0 MB/s  17m22spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 735 MB/4.9 GB  4.0 MB/s  17m22spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 735 MB/4.9 GB  4.0 MB/s  17m22spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 736 MB/4.9 GB  4.0 MB/s  17m21spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 736 MB/4.9 GB  4.0 MB/s  17m21spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 736 MB/4.9 GB  4.0 MB/s  17m21spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 737 MB/4.9 GB  4.0 MB/s  17m21spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 737 MB/4.9 GB  4.0 MB/s  17m21spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 737 MB/4.9 GB  4.0 MB/s  17m21spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 738 MB/4.9 GB  4.1 MB/s   17m1spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 738 MB/4.9 GB  4.1 MB/s   17m0spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 739 MB/4.9 GB  4.1 MB/s   17m0spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 739 MB/4.9 GB  4.1 MB/s   17m0spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 739 MB/4.9 GB  4.1 MB/s   17m0spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 740 MB/4.9 GB  4.1 MB/s   17m0spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 740 MB/4.9 GB  4.1 MB/s   17m0spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 741 MB/4.9 GB  4.1 MB/s   17m0spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 741 MB/4.9 GB  4.1 MB/s   17m0spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 742 MB/4.9 GB  4.1 MB/s   17m0spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 742 MB/4.9 GB  4.1 MB/s  16m52spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 742 MB/4.9 GB  4.1 MB/s  16m52spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 743 MB/4.9 GB  4.1 MB/s  16m51spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 743 MB/4.9 GB  4.1 MB/s  16m51spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 744 MB/4.9 GB  4.1 MB/s  16m51spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 744 MB/4.9 GB  4.1 MB/s  16m51spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 744 MB/4.9 GB  4.1 MB/s  16m51spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 745 MB/4.9 GB  4.1 MB/s  16m51spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 745 MB/4.9 GB  4.1 MB/s  16m51spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 745 MB/4.9 GB  4.1 MB/s  16m51spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 746 MB/4.9 GB  4.1 MB/s   17m2spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 746 MB/4.9 GB  4.1 MB/s   17m2spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 747 MB/4.9 GB  4.1 MB/s   17m2spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 747 MB/4.9 GB  4.1 MB/s   17m2spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 748 MB/4.9 GB  4.1 MB/s   17m2spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 748 MB/4.9 GB  4.1 MB/s   17m2spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 749 MB/4.9 GB  4.1 MB/s   17m2spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 749 MB/4.9 GB  4.1 MB/s   17m2spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 750 MB/4.9 GB  4.1 MB/s   17m1spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 750 MB/4.9 GB  4.1 MB/s   17m1spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 751 MB/4.9 GB  4.1 MB/s  16m54spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 751 MB/4.9 GB  4.1 MB/s  16m54spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 751 MB/4.9 GB  4.1 MB/s  16m54spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 752 MB/4.9 GB  4.1 MB/s  16m54spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 752 MB/4.9 GB  4.1 MB/s  16m54spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 753 MB/4.9 GB  4.1 MB/s  16m54spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 753 MB/4.9 GB  4.1 MB/s  16m54spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 753 MB/4.9 GB  4.1 MB/s  16m54spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 753 MB/4.9 GB  4.1 MB/s  16m54spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 755 MB/4.9 GB  4.1 MB/s  16m53spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 755 MB/4.9 GB  4.1 MB/s  16m53spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 756 MB/4.9 GB  4.2 MB/s  16m36spulling manifest
pulling 667b0c1932bc...  15% ▕██              ▏ 756 MB/4.9 GB  4.2 MB/s  16m36spulling manifest

In [ ]:
import time
import os
import json
import pandas as pd
from tqdm import tqdm
from llm5w1h import NewsArticle
from llm5w1h import LLMConnector
from llm5w1h import NewsAnalyzer

model = "llama3.1"
# model = "gemma2"


def extract_texts(file_path, data_list):
    # extracts specified component from json object
    def extract_component(data, component):
        annotations = data["fiveWoneH"][component]["annotated"]
        texts = [item.get("text") for item in annotations]
        return "; ".join(text for text in texts if text is not None)

    # loads json object from file
    with open(file_path, "r") as file:
        data = json.load(file)

    # extracts true components from the annotated articles (in a json object)
    text = data["text"]
    what_true = extract_component(data, "what")
    where_true = extract_component(data, "where")
    when_true = extract_component(data, "when")
    who_true = extract_component(data, "who")
    why_true = extract_component(data, "why")
    how_true = extract_component(data, "how")

    analyzer = NewsAnalyzer("http://localhost:11434","api_key", model)
    article = NewsArticle(data.get("title"), data.get("description"), text, data.get("date_publish"), data.get("url"))
    analyzer.process_article(article)

    extracted_components = analyzer.extract_components()
    # what_pred = analyzer.identify_component("What")
    # where_pred = analyzer.identify_component("Where")
    # when_pred = analyzer.identify_component("When")
    # who_pred = analyzer.identify_component("Who")
    # why_pred = analyzer.identify_component("Why")
    # how_pred = analyzer.identify_component("How")

    data_list.append({
        "text": text,
        "what_true": what_true,
        "where_true": where_true,
        "when_true": when_true,
        "who_true": who_true,
        "why_true": why_true,
        "how_true": how_true,
        "what_pred": extracted_components["what_pred"],
        "where_pred": extracted_components["where_pred"],
        "when_pred": extracted_components["when_pred"],
        "who_pred": extracted_components["who_pred"],
        "why_pred": extracted_components["why_pred"],
        "how_pred": extracted_components["how_pred"]
    })

In [15]:
data_list = []
extract_texts("./data_samples/0e5fa7c0e6252bfeeea5e3840c6cb503f299c19d24331c4ba60c5974.json", data_list)
print(data_list)

Date: 2016-11-08 14:44:34
Title: While the U.S. talks about election, UK outraged over Toblerone chocolate
Description: Some are even blaming Brexit.
Text: Skip Ad Ad Loading... x Embed x Share Toblerone is facing a mountain of criticism for changing the shape of its famous triangular candy bars in British stores, a move it blames on rising costs. USA TODAY Toblerone chocolate bars come in a variety of sizes, but recently changed the shape of two of its smaller bars sold in the UK. (Photo: Martin Ruetschi, AP) The UK has a chocolate bar crisis on its hands: the beloved Swiss chocolate bar is unrecognizable. Toblerone, the classic chocolate bar with almond-and-honey-filled triangle chunks, recently lost weight. In two sizes, the triangles shrunk, leaving wider gaps of chocolate. Toblerone can you tell me what this is all about... looks like there's half a bar missing! pic.twitter.com/C2VD3DjppE -- Alana Cartwright (@AlanaCartwrigh3) October 29, 2016  @HelenRyles Hi Helen, yes this is just our smaller bar. -- Toblerone (@Toblerone) October 31, 2016  The 400-gram bar was reduced to a 360-gram bar and the 170-gram was reduced to 150 grams. "Like many other companies, we are experiencing higher costs for numerous ingredients ... we have had to reduce the weight of just two of our bars in the UK," the company said on Facebook. People aren't happy about the change. The new #Toblerone. Wrong on so many levels. It now looks like a bicycle stand.#WeWantOurTobleroneBack. pic.twitter.com/C71KeNUWF1 -- James Melville (@JamesMelville) November 8, 2016  So unhappy, in fact, it's outpacing U.S. Election Day news. I'm so happy that readers of BBC News have got their priorities right. #Toblerone#Election2016pic.twitter.com/eeAlvoTqY6 -- David Wriglesworth (@Wriggy) November 8, 2016 It could be the end of the world as we know it. So what are the good folk of Britain talking about? Toblerone. pic.twitter.com/i8ryxmHc5c -- Julia Hartley-Brewer (@JuliaHB1) November 8, 2016 Some blame Brexit. Straight up the worst thing about brexit is Toblerone down sizing -- Alex Littlewood (@Alex_JL29) November 8, 2016 #toblerone#brexit I told you that leaving the EU would have serious consequences. Now I' m really upset. pic.twitter.com/w81cWYpNl4 -- Mark Greenwood (@markcjgreenwood) November 8, 2016 The company denies the change is tied to Brexit, a Mondelez spokeswoman told the BBC. The only bars affected are sold in the UK. Follow Ashley May on Twitter: @ashleymaytweets Read or Share this story: http://usat.ly/2fcLZ18
URL: http://www.usatoday.com/story/money/nation-now/2016/11/08/while-us-talks-election-uk-outraged-over-toblerone-chocolate/93465240/
[{'text': 'Skip Ad Ad Loading... x Embed x Share Toblerone is facing a mountain of criticism for changing the shape of its famous triangular candy bars in British stores, a move it blames on rising costs. USA TODAY Toblerone chocolate bars come in a variety of sizes, but recently changed the shape of two of its smaller bars sold in the UK. (Photo: Martin Ruetschi, AP) The UK has a chocolate bar crisis on its hands: the beloved Swiss chocolate bar is unrecognizable. Toblerone, the classic chocolate bar with almond-and-honey-filled triangle chunks, recently lost weight. In two sizes, the triangles shrunk, leaving wider gaps of chocolate. Toblerone can you tell me what this is all about... looks like there\'s half a bar missing! pic.twitter.com/C2VD3DjppE -- Alana Cartwright (@AlanaCartwrigh3) October 29, 2016  @HelenRyles Hi Helen, yes this is just our smaller bar. -- Toblerone (@Toblerone) October 31, 2016  The 400-gram bar was reduced to a 360-gram bar and the 170-gram was reduced to 150 grams. "Like many other companies, we are experiencing higher costs for numerous ingredients ... we have had to reduce the weight of just two of our bars in the UK," the company said on Facebook. People aren\'t happy about the change. The new #Toblerone. Wrong on so many levels. It now looks like a bicycle stand.#WeWantOurTobleroneBack. pic.twitter.com/C71KeNUWF1 -- James Melville (@JamesMelville) November 8, 2016  So unhappy, in fact, it\'s outpacing U.S. Election Day news. I\'m so happy that readers of BBC News have got their priorities right. #Toblerone#Election2016pic.twitter.com/eeAlvoTqY6 -- David Wriglesworth (@Wriggy) November 8, 2016 It could be the end of the world as we know it. So what are the good folk of Britain talking about? Toblerone. pic.twitter.com/i8ryxmHc5c -- Julia Hartley-Brewer (@JuliaHB1) November 8, 2016 Some blame Brexit. Straight up the worst thing about brexit is Toblerone down sizing -- Alex Littlewood (@Alex_JL29) November 8, 2016 #toblerone#brexit I told you that leaving the EU would have serious consequences. Now I\' m really upset. pic.twitter.com/w81cWYpNl4 -- Mark Greenwood (@markcjgreenwood) November 8, 2016 The company denies the change is tied to Brexit, a Mondelez spokeswoman told the BBC. The only bars affected are sold in the UK. Follow Ashley May on Twitter: @ashleymaytweets Read or Share this story: http://usat.ly/2fcLZ18', 'what_true': 'outraged over Toblerone chocolate', 'where_true': 'in British stores; UK', 'when_true': 'November 8, 2016', 'who_true': 'UK; Toblerone', 'why_true': 'changing the shape of its famous triangular candy bars', 'how_true': 'changed the shape', 'what_pred': 'Toblerone changed the shape of its smaller chocolate bars sold in the UK due to rising costs', 'where_pred': 'UK (specifically British stores)', 'when_pred': 'October 29, 2016 (when the change was first noticed)', 'who_pred': 'Toblerone, a Swiss chocolate company', 'why_pred': 'Due to rising costs for ingredients', 'how_pred': 'The company reduced the weight of two smaller bar sizes from 400-gram and 170-gram to 360-gram and 150 grams, respectively'}]

In [16]:
pd.DataFrame(data_list)

,text,what_true,where_true,when_true,who_true,why_true,how_true,what_pred,where_pred,when_pred,who_pred,why_pred,how_pred
0,Skip Ad Ad Loading... x Embed x Share Tobleron...,outraged over Toblerone chocolate,in British stores; UK,"November 8, 2016",UK; Toblerone,changing the shape of its famous triangular ca...,changed the shape,Toblerone changed the shape of its smaller cho...,UK (specifically British stores),"October 29, 2016 (when the change was first no...","Toblerone, a Swiss chocolate company",Due to rising costs for ingredients,The company reduced the weight of two smaller ...

In [18]:
%pip install bert_score

Collecting bert_score
  Using cached bert_score-0.3.13-py3-none-any.whl.metadata (15 kB)
Collecting torch>=1.0.0 (from bert_score)
  Using cached torch-2.6.0-cp312-cp312-win_amd64.whl.metadata (28 kB)
Requirement already satisfied: pandas>=1.0.1 in c:\users\luqui\appdata\local\programs\python\python312\lib\site-packages (from bert_score) (2.2.3)
Collecting transformers>=3.0.0 (from bert_score)
  Using cached transformers-4.48.2-py3-none-any.whl.metadata (44 kB)
Requirement already satisfied: numpy in c:\users\luqui\appdata\local\programs\python\python312\lib\site-packages (from bert_score) (2.2.2)
Collecting requests (from bert_score)
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: tqdm>=4.31.1 in c:\users\luqui\appdata\local\programs\python\python312\lib\site-packages (from bert_score) (4.67.1)
Collecting matplotlib (from bert_score)
  Using cached matplotlib-3.10.0-cp312-cp312-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: packaging>=20.9 in c:\users\luqui\appdata\roaming\python\python312\site-packages (from bert_score) (24.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\luqui\appdata\roaming\python\python312\site-packages (from pandas>=1.0.1->bert_score) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\luqui\appdata\local\programs\python\python312\lib\site-packages (from pandas>=1.0.1->bert_score) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\luqui\appdata\local\programs\python\python312\lib\site-packages (from pandas>=1.0.1->bert_score) (2025.1)
Collecting filelock (from torch>=1.0.0->bert_score)
  Using cached filelock-3.17.0-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\luqui\appdata\local\programs\python\python312\lib\site-packages (from torch>=1.0.0->bert_score) (4.12.2)
Collecting networkx (from torch>=1.0.0->bert_score)
  Using cached networkx-3.4.2-py3-none-any.whl.metadata (6.3 kB)
Collecting jinja2 (from torch>=1.0.0->bert_score)
  Using cached jinja2-3.1.5-py3-none-any.whl.metadata (2.6 kB)
Collecting fsspec (from torch>=1.0.0->bert_score)
  Using cached fsspec-2025.2.0-py3-none-any.whl.metadata (11 kB)
Collecting setuptools (from torch>=1.0.0->bert_score)
  Using cached setuptools-75.8.0-py3-none-any.whl.metadata (6.7 kB)
Collecting sympy==1.13.1 (from torch>=1.0.0->bert_score)
  Using cached sympy-1.13.1-py3-none-any.whl.metadata (12 kB)
Collecting mpmath<1.4,>=1.1.0 (from sympy==1.13.1->torch>=1.0.0->bert_score)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: colorama in c:\users\luqui\appdata\roaming\python\python312\site-packages (from tqdm>=4.31.1->bert_score) (0.4.6)
Collecting huggingface-hub<1.0,>=0.24.0 (from transformers>=3.0.0->bert_score)
  Using cached huggingface_hub-0.28.1-py3-none-any.whl.metadata (13 kB)
Collecting pyyaml>=5.1 (from transformers>=3.0.0->bert_score)
  Using cached PyYAML-6.0.2-cp312-cp312-win_amd64.whl.metadata (2.1 kB)
Collecting regex!=2019.12.17 (from transformers>=3.0.0->bert_score)
  Using cached regex-2024.11.6-cp312-cp312-win_amd64.whl.metadata (41 kB)
Collecting tokenizers<0.22,>=0.21 (from transformers>=3.0.0->bert_score)
  Using cached tokenizers-0.21.0-cp39-abi3-win_amd64.whl.metadata (6.9 kB)
Collecting safetensors>=0.4.1 (from transformers>=3.0.0->bert_score)
  Using cached safetensors-0.5.2-cp38-abi3-win_amd64.whl.metadata (3.9 kB)
Collecting contourpy>=1.0.1 (from matplotlib->bert_score)
  Using cached contourpy-1.3.1-cp312-cp312-win_amd64.whl.metadata (5.4 kB)
Collecting cycler>=0.10 (from matplotlib->bert_score)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib->bert_score)
  Using cached fonttools-4.55.8-cp312-cp312-win_amd64.whl.metadata (103 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib->bert_score)
  Using cached kiwisolver-1.4.8-cp312-cp312-win_amd64.whl.metadata (6.3 kB)
Collecting pillow>=8 (from matplotlib->bert_score)
  Using cached pillow-11.1.0-cp312-cp312-win_amd64.whl.metadata (9.3 kB)
Collecting pyparsing>=2.3.1 (from matplotlib->bert_score)
  Using cached pyparsing-3.2.1-py3-none-any.whl.metadata (5.0 kB)
Collecting charset-normalizer<4,>=2 (from requests->bert_score)
  Using cached charset_normalizer-3.4.1-cp312-cp312-win_amd64.whl.metadata (36 kB)
Requirement already satisfied: idna<4,>=2.5 in c:\users\luqui\appdata\local\programs\python\python312\lib\site-packages (from requests->bert_score) (3.10)
Collecting urllib3<3,>=1.21.1 (from requests->bert_score)
  Using cached urllib3-2.3.0-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\luqui\appdata\local\programs\python\python312\lib\site-packages (from requests->bert_score) (2025.1.31)
Requirement already satisfied: six>=1.5 in c:\users\luqui\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.1->bert_score) (1.17.0)
Collecting MarkupSafe>=2.0 (from jinja2->torch>=1.0.0->bert_score)
  Using cached MarkupSafe-3.0.2-cp312-cp312-win_amd64.whl.metadata (4.1 kB)
Using cached bert_score-0.3.13-py3-none-any.whl (61 kB)
Downloading torch-2.6.0-cp312-cp312-win_amd64.whl (204.1 MB)
   ---------------------------------------- 0.0/204.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/204.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/204.1 MB ? eta -:--:--
   ---------------------------------------- 0.3/204.1 MB ? eta -:--:--
   ---------------------------------------- 0.5/204.1 MB 762.0 kB/s eta 0:04:28
   ---------------------------------------- 0.5/204.1 MB 762.0 kB/s eta 0:04:28
   ---------------------------------------- 0.8/204.1 MB 798.0 kB/s eta 0:04:15
   ---------------------------------------- 1.0/204.1 MB 838.4 kB/s eta 0:04:03
   ---------------------------------------- 1.0/204.1 MB 838.4 kB/s eta 0:04:03
   ---------------------------------------- 1.3/204.1 MB 860.2 kB/s eta 0:03:56
   ---------------------------------------- 1.6/204.1 MB 892.3 kB/s eta 0:03:48
   ---------------------------------------- 1.8/204.1 MB 915.0 kB/s eta 0:03:42
   ---------------------------------------- 2.1/204.1 MB 946.9 kB/s eta 0:03:34
   ---------------------------------------- 2.4/204.1 MB 965.5 kB/s eta 0:03:29
    --------------------------------------- 2.6/204.1 MB 993.4 kB/s eta 0:03:23
    --------------------------------------- 2.6/204.1 MB 993.4 kB/s eta 0:03:23
    --------------------------------------- 3.1/204.1 MB 1.0 MB/s eta 0:03:18
    --------------------------------------- 3.4/204.1 MB 1.0 MB/s eta 0:03:13
    --------------------------------------- 3.7/204.1 MB 1.1 MB/s eta 0:03:08
    --------------------------------------- 3.9/204.1 MB 1.1 MB/s eta 0:03:04
    --------------------------------------- 4.2/204.1 MB 1.1 MB/s eta 0:03:01
    --------------------------------------- 4.5/204.1 MB 1.1 MB/s eta 0:02:58
    --------------------------------------- 5.0/204.1 MB 1.2 MB/s eta 0:02:51
   - -------------------------------------- 5.2/204.1 MB 1.2 MB/s eta 0:02:49
   - -------------------------------------- 5.5/204.1 MB 1.2 MB/s eta 0:02:47
   - -------------------------------------- 6.0/204.1 MB 1.2 MB/s eta 0:02:42
   - -------------------------------------- 6.3/204.1 MB 1.2 MB/s eta 0:02:39
   - -------------------------------------- 6.6/204.1 MB 1.3 MB/s eta 0:02:38
   - -------------------------------------- 7.1/204.1 MB 1.3 MB/s eta 0:02:33
   - -------------------------------------- 7.3/204.1 MB 1.3 MB/s eta 0:02:32
   - -------------------------------------- 7.9/204.1 MB 1.3 MB/s eta 0:02:28
   - -------------------------------------- 8.1/204.1 MB 1.3 MB/s eta 0:02:27
   - -------------------------------------- 8.7/204.1 MB 1.4 MB/s eta 0:02:23
   - -------------------------------------- 8.9/204.1 MB 1.4 MB/s eta 0:02:21
   - -------------------------------------- 9.4/204.1 MB 1.4 MB/s eta 0:02:19
   - -------------------------------------- 9.7/204.1 MB 1.4 MB/s eta 0:02:18
   -- ------------------------------------- 10.2/204.1 MB 1.4 MB/s eta 0:02:16
   -- ------------------------------------- 10.5/204.1 MB 1.4 MB/s eta 0:02:15
   -- ------------------------------------- 11.0/204.1 MB 1.5 MB/s eta 0:02:12
   -- ------------------------------------- 11.5/204.1 MB 1.5 MB/s eta 0:02:09
   -- ------------------------------------- 11.8/204.1 MB 1.5 MB/s eta 0:02:09
   -- ------------------------------------- 12.3/204.1 MB 1.5 MB/s eta 0:02:08
   -- ------------------------------------- 12.6/204.1 MB 1.5 MB/s eta 0:02:06
   -- ------------------------------------- 13.1/204.1 MB 1.5 MB/s eta 0:02:05
   -- ------------------------------------- 13.6/204.1 MB 1.6 MB/s eta 0:02:03
   -- ------------------------------------- 13.9/204.1 MB 1.6 MB/s eta 0:02:02
   -- ------------------------------------- 14.4/204.1 MB 1.6 MB/s eta 0:02:01
   -- ------------------------------------- 14.9/204.1 MB 1.6 MB/s eta 0:02:00
   --- ------------------------------------ 15.5/204.1 MB 1.6 MB/s eta 0:01:58
   --- ------------------------------------ 15.7/204.1 MB 1.6 MB/s eta 0:01:57
   --- ------------------------------------ 16.3/204.1 MB 1.6 MB/s eta 0:01:56
   --- ------------------------------------ 16.8/204.1 MB 1.6 MB/s eta 0:01:55
   --- ------------------------------------ 17.3/204.1 MB 1.7 MB/s eta 0:01:53
   --- ------------------------------------ 17.8/204.1 MB 1.7 MB/s eta 0:01:51
   --- ------------------------------------ 18.4/204.1 MB 1.7 MB/s eta 0:01:50
   --- ------------------------------------ 18.9/204.1 MB 1.7 MB/s eta 0:01:49
   --- ------------------------------------ 19.4/204.1 MB 1.7 MB/s eta 0:01:48
   --- ------------------------------------ 19.9/204.1 MB 1.7 MB/s eta 0:01:47
   --- ------------------------------------ 20.2/204.1 MB 1.7 MB/s eta 0:01:46
   ---- ----------------------------------- 20.4/204.1 MB 1.7 MB/s eta 0:01:46
   ---- ----------------------------------- 21.0/204.1 MB 1.7 MB/s eta 0:01:46
   ---- ----------------------------------- 21.5/204.1 MB 1.8 MB/s eta 0:01:45
   ---- ----------------------------------- 22.0/204.1 MB 1.8 MB/s eta 0:01:43
   ---- ----------------------------------- 22.5/204.1 MB 1.8 MB/s eta 0:01:43
   ---- ----------------------------------- 23.1/204.1 MB 1.8 MB/s eta 0:01:42
   ---- ----------------------------------- 23.6/204.1 MB 1.8 MB/s eta 0:01:41
   ---- ----------------------------------- 23.9/204.1 MB 1.8 MB/s eta 0:01:41
   ---- ----------------------------------- 24.4/204.1 MB 1.8 MB/s eta 0:01:40
   ---- ----------------------------------- 24.9/204.1 MB 1.8 MB/s eta 0:01:39
   ---- ----------------------------------- 25.4/204.1 MB 1.8 MB/s eta 0:01:38
   ----- ---------------------------------- 26.0/204.1 MB 1.8 MB/s eta 0:01:38
   ----- ---------------------------------- 26.5/204.1 MB 1.8 MB/s eta 0:01:37
   ----- ---------------------------------- 27.0/204.1 MB 1.9 MB/s eta 0:01:36
   ----- ---------------------------------- 27.3/204.1 MB 1.9 MB/s eta 0:01:36
   ----- ---------------------------------- 27.8/204.1 MB 1.9 MB/s eta 0:01:35
   ----- ---------------------------------- 28.3/204.1 MB 1.9 MB/s eta 0:01:35
   ----- ---------------------------------- 28.8/204.1 MB 1.9 MB/s eta 0:01:34
   ----- ---------------------------------- 29.4/204.1 MB 1.9 MB/s eta 0:01:33
   ----- ---------------------------------- 30.1/204.1 MB 1.9 MB/s eta 0:01:32
   ------ --------------------------------- 30.7/204.1 MB 1.9 MB/s eta 0:01:31
   ------ --------------------------------- 31.2/204.1 MB 1.9 MB/s eta 0:01:31
   ------ --------------------------------- 31.7/204.1 MB 1.9 MB/s eta 0:01:30
   ------ --------------------------------- 32.0/204.1 MB 1.9 MB/s eta 0:01:30
   ------ --------------------------------- 32.5/204.1 MB 1.9 MB/s eta 0:01:29
   ------ --------------------------------- 33.0/204.1 MB 1.9 MB/s eta 0:01:29
   ------ --------------------------------- 33.6/204.1 MB 1.9 MB/s eta 0:01:28
   ------ --------------------------------- 33.8/204.1 MB 1.9 MB/s eta 0:01:28
   ------ --------------------------------- 34.3/204.1 MB 1.9 MB/s eta 0:01:28
   ------ --------------------------------- 34.9/204.1 MB 1.9 MB/s eta 0:01:27
   ------ --------------------------------- 35.4/204.1 MB 2.0 MB/s eta 0:01:27
   ------- -------------------------------- 35.9/204.1 MB 2.0 MB/s eta 0:01:26
   ------- -------------------------------- 36.2/204.1 MB 2.0 MB/s eta 0:01:26
   ------- -------------------------------- 36.7/204.1 MB 2.0 MB/s eta 0:01:26
   ------- -------------------------------- 37.2/204.1 MB 2.0 MB/s eta 0:01:25
   ------- -------------------------------- 37.7/204.1 MB 2.0 MB/s eta 0:01:25
   ------- -------------------------------- 38.3/204.1 MB 2.0 MB/s eta 0:01:24
   ------- -------------------------------- 38.8/204.1 MB 2.0 MB/s eta 0:01:24
   ------- -------------------------------- 39.1/204.1 MB 2.0 MB/s eta 0:01:24
   ------- -------------------------------- 39.6/204.1 MB 2.0 MB/s eta 0:01:23
   ------- -------------------------------- 40.1/204.1 MB 2.0 MB/s eta 0:01:23
   ------- -------------------------------- 40.6/204.1 MB 2.0 MB/s eta 0:01:23
   -------- ------------------------------- 41.2/204.1 MB 2.0 MB/s eta 0:01:22
   -------- ------------------------------- 41.4/204.1 MB 2.0 MB/s eta 0:01:22
   -------- ------------------------------- 41.9/204.1 MB 2.0 MB/s eta 0:01:22
   -------- ------------------------------- 42.2/204.1 MB 2.0 MB/s eta 0:01:22
   -------- ------------------------------- 42.7/204.1 MB 2.0 MB/s eta 0:01:21
   -------- ------------------------------- 43.3/204.1 MB 2.0 MB/s eta 0:01:21
   -------- ------------------------------- 43.5/204.1 MB 2.0 MB/s eta 0:01:21
   -------- ------------------------------- 44.0/204.1 MB 2.0 MB/s eta 0:01:21
   -------- ------------------------------- 44.6/204.1 MB 2.0 MB/s eta 0:01:20
   -------- ------------------------------- 44.8/204.1 MB 2.0 MB/s eta 0:01:20
   -------- ------------------------------- 45.4/204.1 MB 2.0 MB/s eta 0:01:20
   -------- ------------------------------- 45.9/204.1 MB 2.0 MB/s eta 0:01:19
   --------- ------------------------------ 46.4/204.1 MB 2.0 MB/s eta 0:01:19
   --------- ------------------------------ 46.7/204.1 MB 2.0 MB/s eta 0:01:19
   --------- ------------------------------ 47.2/204.1 MB 2.0 MB/s eta 0:01:19
   --------- ------------------------------ 47.7/204.1 MB 2.0 MB/s eta 0:01:18
   --------- ------------------------------ 48.2/204.1 MB 2.0 MB/s eta 0:01:18
   --------- ------------------------------ 48.8/204.1 MB 2.0 MB/s eta 0:01:18
   --------- ------------------------------ 49.0/204.1 MB 2.0 MB/s eta 0:01:17
   --------- ------------------------------ 49.5/204.1 MB 2.0 MB/s eta 0:01:17
   --------- ------------------------------ 50.1/204.1 MB 2.0 MB/s eta 0:01:17
   --------- ------------------------------ 50.6/204.1 MB 2.0 MB/s eta 0:01:16
   --------- ------------------------------ 50.9/204.1 MB 2.0 MB/s eta 0:01:16
   ---------- ----------------------------- 51.4/204.1 MB 2.0 MB/s eta 0:01:16
   ---------- ----------------------------- 51.9/204.1 MB 2.0 MB/s eta 0:01:16
   ---------- ----------------------------- 52.2/204.1 MB 2.0 MB/s eta 0:01:16
   ---------- ----------------------------- 52.7/204.1 MB 2.0 MB/s eta 0:01:15
   ---------- ----------------------------- 53.0/204.1 MB 2.0 MB/s eta 0:01:15
   ---------- ----------------------------- 53.5/204.1 MB 2.0 MB/s eta 0:01:15
   ---------- ----------------------------- 54.0/204.1 MB 2.0 MB/s eta 0:01:15
   ---------- ----------------------------- 54.5/204.1 MB 2.0 MB/s eta 0:01:14
   ---------- ----------------------------- 55.1/204.1 MB 2.0 MB/s eta 0:01:14
   ---------- ----------------------------- 55.6/204.1 MB 2.0 MB/s eta 0:01:13
   ---------- ----------------------------- 56.1/204.1 MB 2.0 MB/s eta 0:01:13
   ----------- ---------------------------- 56.4/204.1 MB 2.0 MB/s eta 0:01:13
   ----------- ---------------------------- 56.9/204.1 MB 2.0 MB/s eta 0:01:13
   ----------- ---------------------------- 57.4/204.1 MB 2.0 MB/s eta 0:01:12
   ----------- ---------------------------- 57.9/204.1 MB 2.0 MB/s eta 0:01:12
   ----------- ---------------------------- 58.5/204.1 MB 2.0 MB/s eta 0:01:12
   ----------- ---------------------------- 59.0/204.1 MB 2.1 MB/s eta 0:01:11
   ----------- ---------------------------- 59.5/204.1 MB 2.1 MB/s eta 0:01:11
   ----------- ---------------------------- 60.0/204.1 MB 2.1 MB/s eta 0:01:11
   ----------- ---------------------------- 60.6/204.1 MB 2.1 MB/s eta 0:01:10
   ----------- ---------------------------- 60.8/204.1 MB 2.1 MB/s eta 0:01:10
   ------------ --------------------------- 61.3/204.1 MB 2.1 MB/s eta 0:01:10
   ------------ --------------------------- 61.9/204.1 MB 2.1 MB/s eta 0:01:09
   ------------ --------------------------- 62.4/204.1 MB 2.1 MB/s eta 0:01:09
   ------------ --------------------------- 62.9/204.1 MB 2.1 MB/s eta 0:01:08
   ------------ --------------------------- 63.4/204.1 MB 2.1 MB/s eta 0:01:08
   ------------ --------------------------- 64.0/204.1 MB 2.1 MB/s eta 0:01:07
   ------------ --------------------------- 64.2/204.1 MB 2.1 MB/s eta 0:01:07
   ------------ --------------------------- 64.7/204.1 MB 2.1 MB/s eta 0:01:06
   ------------ --------------------------- 65.3/204.1 MB 2.1 MB/s eta 0:01:06
   ------------ --------------------------- 65.8/204.1 MB 2.1 MB/s eta 0:01:05
   ------------ --------------------------- 66.3/204.1 MB 2.2 MB/s eta 0:01:05
   ------------- -------------------------- 66.8/204.1 MB 2.2 MB/s eta 0:01:04
   ------------- -------------------------- 67.4/204.1 MB 2.2 MB/s eta 0:01:04
   ------------- -------------------------- 67.9/204.1 MB 2.2 MB/s eta 0:01:03
   ------------- -------------------------- 68.2/204.1 MB 2.2 MB/s eta 0:01:03
   ------------- -------------------------- 68.4/204.1 MB 2.2 MB/s eta 0:01:03
   ------------- -------------------------- 68.9/204.1 MB 2.2 MB/s eta 0:01:02
   ------------- -------------------------- 69.2/204.1 MB 2.2 MB/s eta 0:01:02
   ------------- -------------------------- 69.7/204.1 MB 2.2 MB/s eta 0:01:02
   ------------- -------------------------- 70.3/204.1 MB 2.2 MB/s eta 0:01:01
   ------------- -------------------------- 70.5/204.1 MB 2.2 MB/s eta 0:01:01
   ------------- -------------------------- 71.0/204.1 MB 2.2 MB/s eta 0:01:01
   ------------- -------------------------- 71.3/204.1 MB 2.2 MB/s eta 0:01:01
   -------------- ------------------------- 71.8/204.1 MB 2.2 MB/s eta 0:01:00
   -------------- ------------------------- 72.4/204.1 MB 2.2 MB/s eta 0:01:00
   -------------- ------------------------- 72.9/204.1 MB 2.2 MB/s eta 0:01:00
   -------------- ------------------------- 73.4/204.1 MB 2.2 MB/s eta 0:00:59
   -------------- ------------------------- 73.9/204.1 MB 2.2 MB/s eta 0:00:59
   -------------- ------------------------- 74.4/204.1 MB 2.2 MB/s eta 0:00:59
   -------------- ------------------------- 74.7/204.1 MB 2.2 MB/s eta 0:00:59
   -------------- ------------------------- 75.2/204.1 MB 2.2 MB/s eta 0:00:58
   -------------- ------------------------- 75.5/204.1 MB 2.2 MB/s eta 0:00:58
   -------------- ------------------------- 76.0/204.1 MB 2.2 MB/s eta 0:00:58
   --------------- ------------------------ 76.5/204.1 MB 2.2 MB/s eta 0:00:58
   --------------- ------------------------ 77.1/204.1 MB 2.2 MB/s eta 0:00:57
   --------------- ------------------------ 77.6/204.1 MB 2.2 MB/s eta 0:00:57
   --------------- ------------------------ 77.9/204.1 MB 2.2 MB/s eta 0:00:57
   --------------- ------------------------ 78.4/204.1 MB 2.2 MB/s eta 0:00:57
   --------------- ------------------------ 78.9/204.1 MB 2.2 MB/s eta 0:00:56
   --------------- ------------------------ 79.2/204.1 MB 2.2 MB/s eta 0:00:56
   --------------- ------------------------ 79.7/204.1 MB 2.2 MB/s eta 0:00:56

In [19]:
from bert_score import score

c:\Users\luqui\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [22]:
def evaluate(data_list):
    e = []
    for article in data_list:
        cands = [article[component] for component in article if component.endswith("_pred")]
        refs = [article[component] for component in article if component.endswith("_true")]
        # start = time.time()
        P, R, F1 = score(cands, refs, lang="en")
        # end = time.time()
        print(F1)
        print(f"System level F1 score: {F1.mean():.3f}")
        # print("Tempo: ", end-start)
        e.append([article, cands, refs, P, R, F1])

    return e

In [23]:
evaluate(data_list)

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

tensor([0.8680, 0.8872, 0.9155, 0.8451, 0.8311, 0.7976])
System level F1 score: 0.857

[[{'text': 'Skip Ad Ad Loading... x Embed x Share Toblerone is facing a mountain of criticism for changing the shape of its famous triangular candy bars in British stores, a move it blames on rising costs. USA TODAY Toblerone chocolate bars come in a variety of sizes, but recently changed the shape of two of its smaller bars sold in the UK. (Photo: Martin Ruetschi, AP) The UK has a chocolate bar crisis on its hands: the beloved Swiss chocolate bar is unrecognizable. Toblerone, the classic chocolate bar with almond-and-honey-filled triangle chunks, recently lost weight. In two sizes, the triangles shrunk, leaving wider gaps of chocolate. Toblerone can you tell me what this is all about... looks like there\'s half a bar missing! pic.twitter.com/C2VD3DjppE -- Alana Cartwright (@AlanaCartwrigh3) October 29, 2016  @HelenRyles Hi Helen, yes this is just our smaller bar. -- Toblerone (@Toblerone) October 31, 2016  The 400-gram bar was reduced to a 360-gram bar and the 170-gram was reduced to 150 grams. "Like many other companies, we are experiencing higher costs for numerous ingredients ... we have had to reduce the weight of just two of our bars in the UK," the company said on Facebook. People aren\'t happy about the change. The new #Toblerone. Wrong on so many levels. It now looks like a bicycle stand.#WeWantOurTobleroneBack. pic.twitter.com/C71KeNUWF1 -- James Melville (@JamesMelville) November 8, 2016  So unhappy, in fact, it\'s outpacing U.S. Election Day news. I\'m so happy that readers of BBC News have got their priorities right. #Toblerone#Election2016pic.twitter.com/eeAlvoTqY6 -- David Wriglesworth (@Wriggy) November 8, 2016 It could be the end of the world as we know it. So what are the good folk of Britain talking about? Toblerone. pic.twitter.com/i8ryxmHc5c -- Julia Hartley-Brewer (@JuliaHB1) November 8, 2016 Some blame Brexit. Straight up the worst thing about brexit is Toblerone down sizing -- Alex Littlewood (@Alex_JL29) November 8, 2016 #toblerone#brexit I told you that leaving the EU would have serious consequences. Now I\' m really upset. pic.twitter.com/w81cWYpNl4 -- Mark Greenwood (@markcjgreenwood) November 8, 2016 The company denies the change is tied to Brexit, a Mondelez spokeswoman told the BBC. The only bars affected are sold in the UK. Follow Ashley May on Twitter: @ashleymaytweets Read or Share this story: http://usat.ly/2fcLZ18',
   'what_true': 'outraged over Toblerone chocolate',
   'where_true': 'in British stores; UK',
   'when_true': 'November 8, 2016',
   'who_true': 'UK; Toblerone',
   'why_true': 'changing the shape of its famous triangular candy bars',
   'how_true': 'changed the shape',
   'what_pred': 'Toblerone changed the shape of its smaller chocolate bars sold in the UK due to rising costs',
   'where_pred': 'UK (specifically British stores)',
   'when_pred': 'October 29, 2016 (when the change was first noticed)',
   'who_pred': 'Toblerone, a Swiss chocolate company',
   'why_pred': 'Due to rising costs for ingredients',
   'how_pred': 'The company reduced the weight of two smaller bar sizes from 400-gram and 170-gram to 360-gram and 150 grams, respectively'},
  ['Toblerone changed the shape of its smaller chocolate bars sold in the UK due to rising costs',
   'UK (specifically British stores)',
   'October 29, 2016 (when the change was first noticed)',
   'Toblerone, a Swiss chocolate company',
   'Due to rising costs for ingredients',
   'The company reduced the weight of two smaller bar sizes from 400-gram and 170-gram to 360-gram and 150 grams, respectively'],
  ['outraged over Toblerone chocolate',
   'in British stores; UK',
   'November 8, 2016',
   'UK; Toblerone',
   'changing the shape of its famous triangular candy bars',
   'changed the shape'],
  tensor([0.8675, 0.8713, 0.8786, 0.8472, 0.8282, 0.7760]),
  tensor([0.8686, 0.9037, 0.9557, 0.8429, 0.8340, 0.8204]),
  tensor([0.8680, 0.8872, 0.9155, 0.8451, 0.8311, 0.7976])]]

In [24]:
# extracting components for all articles and writing in a spreadsheet
data_list = []
data_folder = './data_samples/'
cnt = 1
for filename in tqdm(os.listdir(data_folder)):
    # print(f"\n{cnt}")
    file_path = os.path.join(data_folder, filename)
    # start = time.time()
    extract_texts(file_path, data_list)
    # end = time.time()
    # print("Tempo: ", end-start)
    cnt += 1
    # if len(data_list) > 5: break
    
df = pd.DataFrame(data_list)
df.to_excel('news_5w1h_llama3.xlsx', index=False)
df.to_csv('news_5w1h_llama3.csv', index=False, encoding='utf-8')

  0%|          | 0/96 [00:00<?, ?it/s]

Date: 2016-11-06 00:00:00
Title: Comey to country: The jury will disregard...
Description: "Never mind," the FBI director says on Clinton's emails.
Text: FBI Director James B. Comey. (MICHAEL REYNOLDS/European Pressphoto Agency) If you have ever watched a procedural crime drama, you probably recognize the words, "the jury will disregard." It is the instruction judges give jurors to ignore inadmissible testimony after it has already been offered in open court. Of course the jury, composed of human beings, cannot forget what it has already heard -- even if they try. The integrity of the proceedings have already been damaged. Director James B. Comey announced Sunday that the FBI's sweep through a fresh cache of emails related to Hillary Clinton's private server found ... nothing big -- the agency concluded once again that the Democratic nominee does not deserve to be charged with a crime. The news comes a little over a week after he revealed that the FBI had found the email cache -- and said little else. In the intervening time, Donald Trump and other top Republicans insisted Comey had obviously found something damning. Headlines about the FBI reopening its probe against Clinton swirled. Leaks from within the FBI muddied the political waters further. Yet the speed with which the FBI reviewed the material that produced this explosion of speculation suggests it must have been irrelevant or copies of emails previously reviewed. In other words, Comey is now asking the voters to disregard the fog of suspicion he created around Clinton. Voters in Pennsylvania and Ohio weigh in on FBI Director James Comey's decision to send a letter to members of Congress informing them that newly discovered emails were either duplicates or personal emails that were not related to government business from Hillary Clinton's time as secretary of state. (Peter Stevenson,Erin Patrick O'Connor,Whitney Leaming/The Washington Post) It's too late. Millions of voters cast ballots over the last week. Many others have no doubt spent the time conceptualizing the race as one between a crook and a crazy man. It turns out that the race is in fact between a relatively conventional politician who has been for decades accused of grand crimes, and a dangerous man who has substantiated many of the alarming claims made about him. For his part, over the past week Trump has run a markedly more restrained, competent campaign. No matter what else it did, Comey reopening the email issue appears to have reinvigorated Trump's once-flagging effort. From here, it is not even clear that Comey's 11th-hour exoneration will help Clinton on Election Day. Though the big story of the race should be that a plainly unqualified man is scarily close to the presidency, the news cycle will spend another day dwelling on Clinton, emails, the roiling emotions in the FBI about the case, and, because of Trump and his propagandists, whether the FBI director is part of a conspiracy to rig the system to help Clinton. Even if Clinton pulls through, as polls suggest is likely, the damage will still be substantial. Republicans have used the Comey affair as pretext to publicly discuss impeaching Clinton, arguing that if it seems as though an indictment is looming, Congress will step in to remove the president. Though no indictment is now coming, Republican politicians have already stoked expectations that they will push for impeachment. Even if they resist doing so, Comey's behavior will become more "evidence" that the system is "rigged," fueling the right-wing grievance machine and the coming campaign to declare Clinton's presidency illegitimate. A Clinton first term was always going to be tough, marked by deep political divisions. After Comey's actions, it will be even harder for Republicans to do anything but assail and prosecute Clinton to the extent the legislative branch can -- regardless of what the country actually needs from its leaders. Then there is the already well-documented damage that Comey's behavior and the leaks that followed it did to the image of the FBI as an apolitical law enforcement organization. Comey may have felt boxed in, trapped in a promise he made to Congress to keep lawmakers informed of any developments in the Clinton email investigation. But there is a reason why law enforcement agencies keep out of electoral politics except when absolutely necessary. There is a reason why, when they must say something, they have an obligation to be careful about what they make public and how. Not, as Comey did, dropping a vague note near the end of a hot presidential campaign that insufficiently stressed that the new email cache may have nothing of relevance in it. The damage -- both to the interests of justice and the integrity of our democracy -- can be substantial, wide-ranging and impossible to disregard.
URL: https://www.washingtonpost.com/blogs/post-partisan/wp/2016/11/06/comey-to-country-the-jury-will-disregard/?utm_term=.914ce12b2617

  1%|          | 1/96 [00:31<49:07, 31.03s/it]

Date: 2016-11-09 03:35:23
Title: Lady Gaga stages protest outside Trump Tower after US election result
Description: There was misery for Hillary Clinton's band of Hollywood megafans as Donald Trump emerged victorious.
Text: After the defeat Hillary superfan Katy Perry said on Twitter 'we are not a nation that will let HATE lead us' 'Sometimes you just have to agree to disagree and grab some p***y', she tweeted before it was swiftly deleted Demi Lovato was forced to apologize for making an insensitive election joke at Trump's expense Scores of celebrities who support Hillary Clinton took to Twitter to express their dismay at the result She was seen clinging to a sanitation truck with a sign 'Love Trumps Hate' There was misery for Hillary Clinton's band of Hollywood megafans as Donald Trump emerged victorious as American President. Lady Gaga staged a protest against Trump outside Trump Tower, clinging to a sanitation truck with a sign 'Love Trumps Hate'. She was then pictured looking emotional in a luxury black Rolls-Royce Phantom being driven away clasping her hands together. At midnight, she had taken to Twitter and wrote: 'Say a prayer America.' Just hours before Trump cinched his victory, Demi Lovato was forced to apologize for making an insensitive election joke. The singer, a vocal Clinton supporter, tweeted yesterday: 'Sometimes you just have to agree to disagree and grab some p***y', referring to Donald Trump's notorious lewd comments in leaked Access Hollywood tapes. Scroll down for video Lady Gaga waves a poster saying 'Love Trumps Hate' in protest as she clings onto a New York City sanitation truck in the early hours of Wednesday  Gaga later posted the photo of her outside Trump Tower on Instagram Lady Gaga was pictured looking depondent in a black Rolls-Royce Phantom after staging a protest with a sanitation truck outside Trump tower Lovato swiftly deleted the tweet after facing backlash from her fans and by 5pm yesterday, she issued an apology saying she was just trying to make 'light of the election.' 'I apologize for the joke I made earlier.. seemed to offend some people,' added the singer, who has previously urged fans to vote in the election tweeting that she was #WithHer. Other famous Clinton supporters took to social media to express their dismay. Eva Longoria captioned an unhappy selfie on Snapchat 'What is happening?????!!!!!'. And Lindsay Lohan went as far as calling for a recount of votes. Just hours before Trump cinched his victory, Demi Lovato (pictured) was forced to apologize for making an insensitive election joke The singer, a vocal Clinton supporter, tweeted yesterday: 'Sometimes you just have to agree to disagree and grab some p***y', referring to Donald Trump's notorious lewd comments in leaked Access Hollywood tapes Lovato swiftly deleted the tweet after facing backlash from her fans and by 5pm yesterday, she issued an apology saying she was just trying to make 'light of the election' Many of of Hillary's supporters including Lena Dunham, Miley Cyrus and Amy Schumer, said they will leave the United States if Trump was elected. Canada took to Twitter to welcome them, writing that immigrants are 'encouraged to bring their cultural traditions with them and share them with their fellow citizens.' And the country's immigration website kept crashing as a Trump victory looked imminent and thousands went online seeking a way out of the country. And as Trump triumphed, scores of celebrities took to social media to express their disappointment and despair. Scores of celebrities took to social media to express their disappointment and despair Lindsay Lohan, who famously tweeted throughout the EU referendum, has told her Twitter fans to retweet if they want a recount of votes in the US election Lohan later posted on Instagram urging people to not worry about what happened on Tuesday Rosie O'Donnell, one of Trump's most vocal opponents, reached out to God on Twitter after the election results 'What is happening?????!!!!!' Eva Longoria captioned this unhappy selfie on Snapchat Katy Perry speaks at Clinton's election night party at the Jacob K. Javits Convention Center Among them, Katy Perry, who has 94million followers, wrote on Twitter in the early hours: 'Do not sit still. Do not weep. MOVE. We are not a nation that will let HATE lead us.' She added: 'WE WILL NEVER BE SILENCED. #LOVETRUMPSHATE.' Perry had earlier revealed her parents voted for Trump, while her Hollywood pals began to panic on Twitter when the election results weren't going the Democratic nominee's way. The Rolling Stones previously told Trump to stop playing their songs during his presidential campaign. In the early hours, Perry tweeted to her 94million followers: 'Do not sit still. Do not weep' 'She would have protected you': Amy Schumer expressed her anger at what she labeled weak Trump voters 'The worst thing is to lose hope': Jennifer Lopez shared a touching message Seeing the funny side: Rumer Willis tried to lighten the mood Somber: Justin Theroux expressed his thoughts on the result with a 9.11 style memorial 'Worst day': Rapper Snoop Dogg had a similar sentiment to Theroux Miley Cyrus was tearful but asked for unity and implored the new president to accept that global warming is real Nothing to say: Jessica Alba's Instagram went dark on hearing the news 'Hold on to each other': Reality star Kris Jenner had a message of equality and respect for her followers 'How could this have happened': Hilaria Baldwin wrote an impassioned message about how scared she was for her children 'We are with you': Actress Amber Tamblyn showed her support for Hillary in the aftermath of the shocking result 'The Rolling Stones have never given permission to the Trump campaign to use their songs and have requested that they cease all use immediately,' they said in a statement in May. But that didn't stop the Republican playing 'You Can't Always Get What You Want' after his victory speech on Wednesday. Mick Jagger reacted on Twitter, joking: 'Just was watching the news... maybe they'll ask me to sing 'You Can't Always Get What You Want' at the inauguration, ha!' Kylie Jenner shared this image which she didn't caption 'I'm confused': Paris Jackson said she felt speechless and scared Ricky Gervais joked that Canada has started building a wall to keep Americans out after news emerged that the Canadian immigration website had crashed following Trump's election One word: Simply put, Olivia Wilde was devastated The Daily Show host Trevor Noah joked: 'Chris Christie is the guy who invested in Apple stock when it was still 5 dollars. I'm stunned.' And Leah Dunham posted a video on Instagram at around 11pm, in which she and Lady Gaga told their followers: 'We still believe.' And in an interview with DailyMail.com, singer Cher said: 'I feel like there's a death in my family.' Drew Barrymore saw the situation as an opportunity to move forward Shame: Rose McGowan was defiant in her message alongside a picture of the Statue of Liberty with head in hands Pop star Lilly Allen weighed into election result saying 'tomorrow we take our world back' Allen joked that perhaps it is time to learn Russian after Trump was elected president Mad Men star January Jones posted this picture of her character on Instagram with the caption: 'How do we explain this to our children? #atleastpotisnowlegaleverywhere #gonnaneedit' Celebrities took to Twitter to share their dismay as a Donald Trump victory looked imminent Frozen star Kristen Bell, who has previously clashed with Trump on Twitter, posted this photo of Martin Luther King, Jr. with a message to 'never forget' what happened in Nazi Germany She added: 'I saw this happen with Brexit. I was in London watching Brexit, and I saw it happen. And I kept trying to tell people, this is like Brexit. Trump is Brexit. And it's just the strangest thing. 'I've been alive for 12, 11 presidents, and I've never seen anything like him, and I understand why the world is terrified that he's now going to be the President of the United States.' 'I'm freaking out too but, together, we are gonna be OK, we got each other, animals, don't lose your s***. Worst case, let's all move to New Zealand,' wrote Kesha alongside a selfie on Instagram. 'This is an embarrassing night for America. We've let a hatemonger lead our great nation. We've let a bully set our course. I'm devastated,' wrote Captain America star Chris Evans. The Big Bang Theory actor Kunal Nayyar added: 'Never in 15 years of living In this country have I ever felt afraid to look like I do. #immigrant.' 'i'm freaking out too but, together, we are gonna be OK, we got each other, animals, don't lose your s***. Worst case, let's all move to New Zealand,' wrote Kesha on Instagram Kesha followed up by sharing a message from actor Conrad Ricamora who stars on How To Get Away With Murder Shocked and shaken: Jessica Chastain wrote of how she worries about her daughter's future while sharing a snap of the tot sleeping 'Well this is utterly terrifying,' said Ariana Grande, adding: 'I am in tears.' 'It shouldn't be this close,' said Khloe Kardashian. 'Where is #OliviaPope when you need her,' joked Demi Lovato, referring to the White House fixer played by Kerry Washington on ABC drama Scandal. 'The positive element from all this is that we can no longer pretend that we are free of racism & sexism. The question is, what do we do now?' wrote Jessica Chastain. Mandy Moore wrote: 'I am just absolutely beside myself right now. I can't believe the way this thing has turned. Trying to remain hopeful but geeez louise.' 'What I've learned so far tonight: America is WAAAAAAAAY more sexist than it is racist. And it's pretty f****** racist. #ElectionNight,' wrote Patton Oswalt. Celebrities including Trevor Noah and Chrissy Teigen took to Twitter to share their reactions Knocked Up producer Judd Apatow said philosopher Noam Chomsky predicted the result Scandal creator Shonda Rhimes exclaimed: 'Really, people? ANYONE can be President? ANYONE? ANY-ONE? 'No but seriously: THIS many of you don't mind the body-part grabbing xenophobic man who says 'there's my black over there?'' Rashida Jones said: 'I just want to remind everyone that we are looking at a very close race with a presidential candidate who was endorsed by the KKK.' John Cho added: 'Entering a depression I've not known before. It is deep and wide and scary.' 'Someone give me hope,' added Sarah Silverman. Jeremy Bronson wrote: 'So how does this work? If we flee the country, do we use our current passports or do we wait for Russia to issue us new ones?' Perry addressed the audience at Clinton's election night party at the Jacob K. Javits Convention Center in New York City pleading for last-minute voters to vote Clinton Lady Gaga shared a picture giving the thumbs up alongside Lena Dunham on Twitter Later on in the evening, the singer was pictured alongside Billie Jean King looking less enthusiastic Mandy Moore and Jessica Chastain were among celebrities expressing their dismay on Twitter 'We are staring into the face of our darkest self America. Why does it have to have a dyed combover??' joked Connie Britton. Earlier in the evening, Perry addressed the audience at Clinton's election night party at the Jacob K. Javits Convention Center in New York City. She pleaded with voters in states that had not closed off their ballot boxes to rush out and vote for Clinton as the results went south for the White House hopeful. 'First and foremost if, you are in a state, and you're watching this and your polls are still open, you must vote for Hillary Clinton tonight!' she begged. Perry said that her Republican parents voted for Trump. Her parents Keith Hudson and Mary Perry are born again Christians and the singer has previously spoken of her strict upbringing. 'But you know what, we will still all be sitting at the same table for Thanksgiving,' she added. 'And this is the moment we need to remember that we all love our parents, and we all love our children. Hollywood began to panic on Twitter that the election results weren't going the Democratic nominee's way The Rolling Stones previously told Trump to stop playing their songs during his campaign. But that didn't stop him playing 'You Can't Always Get What You Want' after his victory speech. Now Mick Jagger has made him an offer... Nigella Lawson said that the results of the US election came down to 'racism' and that 'confederate flags will be flying' Lord Sugar commented on his The Apprentice counterpart's victory, saying 'the markets are stable' Canada took to Twitter to welcome immigrants, saying they are 'encouraged to bring their cultural traditions with them and share them with their fellow citizens' Miley Cyrus broke down in tears in a video posted on Twitter as she talked about the election results 'And I can rest easy knowing that both of my young nieces at home will never see themselves less than equal - anything other than equal.' The pop star has performed for Clinton at several rallies in the past year, including one on Saturday night in Philadelphia. But she did not soothe nervous Clinton supporters gathered outside the Javits Convention Center in New York City tonight with a song. Instead, she read aloud from a piece paper she brought with her to the stage. A victory for Clinton tonight 'will be proof that America is great,' Perry proclaimed. CELEBRITIES WHO PLEDGED TO LEAVE IF TRUMP WON LENA DUNHAM The Girls star said she'd move to Canada if Trump won the presidency. 'I love Canada. I think that it's a great place, and there's an area in Vancouver that I find beautiful and appealing, and I can conduct business from there,' she said. BARBRA STREISAND Streisand suggested she would move to Australia or Canada if Trump emerged the victor on Election Day. 'I can't believe it. I'm either coming to your country if you'll let me in, or Canada,' the singer told 60 Minutes in August. AMY SCHUMER Comedian and actress Amy Schumer said she would head for Spain if Trump won. 'My act will change because I will need to learn to speak Spanish because I will move to Spain or somewhere,' she told BBC's Newsnight. 'It's beyond my comprehension if Trump won. It's just too crazy.' SAMUEL L. JACKSON 'If that motherf***** becomes president, I'm moving my black a** to South Africa,' the actor said on Jimmy Kimmel. CHELSEA HANDLER The talk show host revealed she had already bought a house in another county just in case Trump won. 'I did buy a house in another country just in case,' Handler said in an interview on ABC's Live with Kelly and Michael in May. 'So all these people that threaten to leave the country and then don't - I actually will leave that country.' BRYAN CRANSTON The Breaking Bad actor said he would 'definitely' move if Trump won, suggesting a permanent vacation to Vancouver. 'I would definitely move. It's not real to me that that would happen. I hope to God it won't,' Cranston said in October. JON STEWART Stewart told People magazine that he would think about 'getting in a rocket and going to another planet because clearly this planet's gone bonkers.' CHER Singer Cher has a similar idea. 'IF HE WERE TO BE ELECTED, I'M MOVING TO JUPITER,' she said on Twitter last year. REV AL SHARPTON The civil rights activist told the audience at a Center for American Progress event in February that he would be looking for flights if Trump won. 'I'm also reserving my ticket to get out of here if he wins. Only because he'd probably have me deported anyhow,' Sharpton said. MILEY CYRUS The singer called Trump a 'f****** nightmare' and pledge to leave the US if he won in a couple of Instagram posts. Katy Perry cheerfully Snapchatted from inside an elevator earlier on Tuesday evening BBC presenter Anita Rani (left) posted a picture on Instagram suggesting someone should start a campaign for Michelle Obama to become president in 2020. And British presenter Chloe Madeley (right) mocked Trump Irish television presenter Amanda Byram posted a map of Ireland saying 'Trump to the left of me, Brexit to the right. Here I am, stuck in the middle with you'.
URL: http://www.dailymail.co.uk/news/article-3918926/Hollywood-starts-panic-results-aren-t-going-Clinton-s-way.html

  2%|▏         | 2/96 [01:12<57:48, 36.89s/it]

Date: 2016-11-12 15:25:02
Title: Hillary Clinton Blames F.B.I. Director for Election Loss
Description: Mrs. Clinton said on Saturday that the announcement by James B. Comey 11 days before the election that he had revived the inquiry into her use of a private email server caused her to lose.
Text: Her campaign said the seemingly positive outcome had only hurt it with voters who did not trust Mrs. Clinton and were receptive to Mr. Trump's claims of a "rigged system." In particular, white suburban women who had been on the fence were reminded of the email imbroglio and broke decidedly in Mr. Trump's favor, aides said. After leading in polls in many battleground states, Mrs. Clinton told the donors on Saturday, "we dropped, and we had to keep really pushing to regain our advantage, which going into last weekend we had." "We were once again up in all but two of the battleground states, and we were up considerably in some that we ended up losing," Mrs. Clinton said. "And we were feeling like we had to put it back together." Presidential candidates have a long history of blaming forces outside their control for their losses. In 2004, John Kerry linked his defeat to a videotape of Osama bin Laden that appeared days before the election, stoking fears about terrorism. In 2012, Mitt Romney told donors he had lost because President Obama had vowed to bestow "gifts" on Democratic special interests groups, namely African-Americans, Hispanics and young people. Mrs. Clinton's contention appears to be more rooted in reality -- and hard data. An internal campaign memo with polling data said that "there is no question that a week from Election Day, Secretary Clinton was poised for a historic win," but that, in the end, "late-breaking developments in the race proved one hurdle too many for us to overcome." Mrs. Clinton lost narrowly in several battleground states, and by the time all ballots are counted, she appears poised to win the popular vote by more than two million votes. Still, Mrs. Clinton's instinct to shun any personal responsibility angered some Democrats. Several donors on the call, while deeply bitter about Mr. Comey's actions, said they believed that Mrs. Clinton and her campaign had suffered avoidable missteps that handed the election to an unacceptable opponent. They pointed to the campaign's lack of a compelling message for white working-class voters and to decisions years ago by Mrs. Clinton to use a private email address at the State Department and to accept millions of dollars for speeches to Wall Street. "There is a special place in hell for Clinton staff, allegedly including Cheryl Mills, that okayed the email server setup," Jim Manley, a Democratic strategist and former senior aide to Senator Harry Reid of Nevada, wrote on Sidewire, a social media site, referring to a longtime aide and lawyer to Mrs. Clinton. Mrs. Clinton's campaign was so confident in her victory that her aides popped open Champagne on the campaign plane early Tuesday. But that conviction, aides would later learn, was based largely on erroneous data showing that young, black and Latino voters and suburban women who had been turned off by Mr. Trump's comments but viewed Mrs. Clinton unfavorably would turn out for her in higher numbers than they ultimately did. Exit polls conducted by Edison Research found that among people who said they had decided in the final week before Election Day, 47 percent voted for Mr. Trump and 42 percent for Mrs. Clinton. As early as Wednesday morning, aides began to explain to Democrats shaken by the loss that the campaign's sophisticated data modeling had not taken into account the bombshell F.B.I. announcement. Mr. Comey's letters to Congress went against the F.B.I.'s longstanding tradition of avoiding decisions that could affect elections, but he told aides that he felt he had no choice because he had already weighed in on the case so publicly. In July, he had taken the unusual step of publicly announcing that the F.B.I. would not charge Mrs. Clinton. At the time, she believed she had finally put the issue to rest. And after the final debate on Oct. 19 in Las Vegas, she emerged in such a strong position that she began to focus on campaigning for down-ballot Democrats and planned a campaign stop in traditionally Republican Arizona. "We felt so good about where we were," Mrs. Clinton told donors. Before Mr. Comey's first letter to Congress, she added, "we just had a real wind at our back." Mr. Trump seized on the letter, telling voters in Nevada the Saturday before Election Day that "the F.B.I. has reopened its criminal investigation into Hillary Clinton," and that the matter "would grind government to a halt" should Mrs. Clinton win the White House. The F.B.I.'s examination of the new emails did not in fact reopen the investigation. Democratic pollsters attributed Mr. Trump's laser-thin victories in Pennsylvania, Michigan and Wisconsin -- states that President Obama had won -- largely to a drifting of college-educated suburban women to the Republican nominee at the last minute, because of the renewed focus on Mrs. Clinton's email server. "We lost with college-educated whites after leading with them all summer," a Clinton spokesman, Brian Fallon, said on Wednesday. "Five more days of reminders about Comey, and they gravitated back to Trump." Before Mrs. Clinton spoke on Saturday, her finance director, Dennis Cheng, thanked the donors on the call, each of whom had raised at least $100,000. The campaign brought in nearly $1 billion to spend heavily on data efforts, to disperse hundreds of staff members to battleground states, and to air television advertisements -- only to fall short to Mr. Trump's upstart operation. Donors conceded that, ultimately, no amount of money could match Mr. Trump's crisp pitch, aimed at the economically downtrodden, to "make America great again." "You can have the greatest field program, and we did -- he had nothing," said Jay S. Jacobs, a prominent New York Democrat and donor to Mrs. Clinton. "You can have better ads, paid for by greater funds, and we did. Unfortunately, Trump had the winning argument." Mrs. Clinton has kept a low profile since her concession speech at a Midtown Manhattan hotel on Wednesday. On Thursday, a young mother with her 13-month-old daughter spotted Mrs. Clinton walking her dogs near her home in Chappaqua, N.Y., posting a photo of the defeated candidate on Facebook that quickly went viral along with the hashtag #ImStillWithHer. On Friday night, Mrs. Clinton thanked volunteers on a nationwide conference call. "Look, I'm not going to sugarcoat it," she said, sighing. "These have been very, very tough days."
URL: http://www.nytimes.com/2016/11/13/us/politics/hillary-clinton-james-comey.html

  3%|▎         | 3/96 [01:39<50:30, 32.59s/it]

Date: 2016-11-11 08:42:13
Title: Taliban attacks German consulate in northern Afghan city of Mazar-i-Sharif with truck bomb
Description: The death toll from a powerful Taliban truck bombing at the German consulate in Afghanistan's Mazar-i-Sharif city rose to at least six Friday, with more than 100 others wounded in a major militant assault.
Text: The death toll from a powerful Taliban truck bombing at the German consulate in Afghanistan's Mazar-i-Sharif city rose to at least six Friday, with more than 100 others wounded in a major militant assault. The Taliban said the bombing late Thursday, which tore a massive crater in the road and overturned cars, was a "revenge attack" for US air strikes this month in the volatile province of Kunduz that left 32 civilians dead. The explosion, followed by sporadic gunfire, reverberated across the usually tranquil northern city, smashing windows of nearby shops and leaving terrified local residents fleeing for cover. "The suicide attacker rammed his explosives-laden car into the wall of the German consulate," local police chief Sayed Kamal Sadat told AFP. All German staff from the consulate were unharmed, according to the foreign ministry in Berlin.
URL: http://www.telegraph.co.uk/news/2016/11/10/taliban-attack-german-consulate-in-northern-afghan-city-of-mazar/

  4%|▍         | 4/96 [01:59<42:33, 27.75s/it]

Date: 2016-11-12 11:53:30
Title: Police name final three victims of Croydon tram crash that killed seven
Description: Police investigating the Croydon tram crash have named the final three victims as Donald Collett, Philip Logan and Robert Huxley.
Text: Police investigating the Croydon tram crash have named the final three victims as Donald Collett, Philip Logan and Robert Huxley. A total of six men and one woman died in the crash when the tram overturned as it entered a bend at high speed. The family of Mr Collett, 62, from Croydon, said he could 'light up a room with his smile'. A statement read: 'Don was a well loved, funny and generous man, who could light up a room with his smile. He is tragically leaving behind a loving family, partner, adored friends and work colleagues. 'Please rest in peace and know you are truly loved and greatly missed.' Mr Logan's family said he was a 'true family man' and a 'generous friend'. A statement from the family read: ' Philip Logan known to all who knew him as Loag, a loving husband to Marilyn, brother to Susan, father to Lee, Tracy, Lisa and Adele, grandfather and great grandfather. 'He was a true family man and generous friend to all with a magnificently dry sense of humor. 'Phil was a man with more love compassion and zest for life than words can express. He will be immensely missed by all that knew him.' The tram's driver was arrested on suspicion of manslaughter and quizzed by investigators who revealed the vehicle was travelling 'significantly' above the permitted speed. He was later released on bail. Scroll down for video Donald Collett, 62, of Croydon (left); and Philip Logan, 52, from New Addington, South London, who died in the crash Dane Chinnery (pictured left), Mark Smith (centre left), Phil Seary (centre right) and Dorota Rynkiewicz (far right) all died in the Croydon tram crash Rail workers at the site work to fix the track where the tram derailed on Wednesday which saw seven people killed Repair work continues on the section of track where a tram crashed, killing seven people, in Croydon, south London Floral tributes left for victim Mark Smith near the Sandilands tram stop by the site of the Croydon tram crash British Transport Police said Donald Collett, 62, of Croydon; Philip Logan, 52, and Robert Huxley, 63, both of New Addington, died in the accident when the tram overturned A resident observes the flowers left near the tram stop where seven people were killed on Wednesday People lay flowers at the scene where the tram crash - six men and one woman died in the crash A Crystal Palace shirt for fans Dane Chinnery and Phil Seary are laid in memory of the pair who died in the crash Floral tributes and Crystal Palace flags and shirts are laid near the scene where a tram crash on Wednesday There was a march for the victims, with many wearing Crystal Palace colours (pictured in the tribute) A group of up to 100 people on Saturday marched down the road carrying banners, flags and flowers to the spot where hundreds of bouquets had already been laid for the victims of the derailing in south London. People spilled out onto the road as they hugged each other and looked at the tributes that had been laid near to the site where the tram crashed during the morning commute on Wednesday. The tram has been removed and repair work on the track has started. An operation to remove the 100 feet-long articulated tram began late last night, with the sections craned onto a flatbed lorry earlier on Saturday. Among the dead were a mother with two young children, a new father, a teenager and a grandfather on his way to work after swapping shifts. Many in Saturday's march were wearing Crystal Palace football colours while some of the bouquets laid were red and blue to reflect the team's colours. Two of the victims - 19-year-old Dane Chinnery and Philip Seary, 57 - were fanatical fans of the club. Friends and family clapped for one minute as they thought about those who had lost their lives in the derailment, ending by singing, 'They're one of our own'. It comes as police revealed they have launched an investigation into claims another tram almost derailed the week before. The tram which crashed in Croydon killing seven people was removed from the scene this morning The tram is taken away from the scene on Saturday as a police probe claimed another almost derailed the week before Investigators said the tram was going significantly faster than the 12mph speed limit as it took a sharp corner The only woman victim, Dorota Rynkiewicz, 35, who had two young daughters, was described by friends as a devoted mother and a 'friendly, caring and giving person'. Her husband Andrzej, a professional golfer, was too upset to talk at the family home in New Addington, Croydon. The couple had moved to the UK from Poland 10 years ago for a 'better life'. Colleagues who started a crowdfunding page to raise PS5,000 for her family said Ms Rynkiewicz was 'loved by many people'. Mother-of-two Dorota Rynkiewicz, pictured with golfer husband Andrzej, was described by friends as a devoted mother and a 'friendly, caring and giving person' Tributes have also been paid online to young father Mark Smith, pictured with fiancee Indre Novikovaite and son Lucas, described as someone who 'could always make anyone laugh' Mr Smith, left with Miss Novikovaite and right with son Lucas, was described as a keen fisherman by friends on social media Another victim was named by police as Mark Smith, 35, from Croydon, who had an 18-month old son with his fiancee Indra Novikovaite and the couple planned to marry next year. The couple had been going out for four years. Her brother said: 'My sister is completely devastated by this.' His cousin, Tom Smith, said: 'Still cannot believe this is true, the last couple of days have just felt like a nightmare. 'The thought that we are all never gonna see you or hear from you again makes me feel sick. We are all in bits.' Mr Smith was on his way to work as a glazier when the speeding tram careered off the tracks and flipped over. Phil Seary (left) pictured at the wedding of his youngest daughter Karina who married Darren Mimms Mr Seary's son-in-law revealed he had only been on the tram on Wednesday morning after agreeing to cover a colleague's shift at his job as an electrical engineer at the Royal Opera House, because he was 'such a kind man' Tributes poured in for Dane Chinnery, left and right with his mother Beverley, a 19-year-old Crystal Palace fan who was killed in the tram crash in Croydon The family of Royal Opera House worker Phil Seary, 57, described him as a 'much loved wonderful son, faithful husband, a loving and doting father and a gentle giant grandfather'. They added: 'He will be immensely missed by all that had the great fortune to know him.' Mr Seary's son-in-law Darren Mimms said he was on his way to work to cover a shift. He said: 'As Phil was such a kind man he would do anything to help anybody. It's really hurting his wife Ann. He shouldn't have been on that tram. He found out the day before he had to go into work that day. 'If he hadn't have been at work he would have been doing bits and bobs around the house and looking after his granddaughter. Ann's not blaming anybody. 'Ann is really hoping to wake up from this horrible dream. She was planning to retire next year. She has worked as a teaching assistant at Rowdown Primary School for 27 years. 'They were hoping to go travelling. Being American she wanted to see more of Europe and that was their plan. We are in complete devastated shock.' Crystal Palace supporter Mr Seary, also known as 'Tank', had three daughters Martha, 43, Erica, 31, Karina, 29, four grandchildren, four great grandchildren and another on the way. Dane Chinnery, a 19-year-old Crystal Palace fan described as a 'friendly, genuine lad', was the first victim to be identified following the crash. Rail workers begin recovery work on the tram rail lines junction at the site of the Croydon tram crash Floral tributes left near the Sandilands tram stop as police probe claims another almost derailed near the location last week The damaged tram carriage was wrapped in tarpaulin last night and removed from the scene on Friday morning Investigators said they expect an interim report on the disaster to be released next week Recovery workers at the site of the crash. The wrecked carriages were covered in blue tarpaulin before they were taken away Firefighters lowered their heads as a mark of respect towards those killed and injured in Wednesday's crash Members of the Armed Forces and emergency services joined the Royal British Legion for the remembrance ceremony Forensic teams and accident investigators have been sweeping the scene for much of the past 48 hours as they try to establish the exact cause of the crash The driver of the tram, a 42-year-old man from Beckenham, was released on bail after being arrested on Wednesday on suspicion of manslaughter over the crash. It occurred at around 6.10am on Tuesday on a sharp bend near the Sandilands stop as the vehicle travelled from New Addington to Wimbledon. Investigators said the tram was travelling at a 'significantly higher speed' than the 12mph speed limit and are probing whether the driver had fallen asleep or was on his phone. Detectives are also examining a report that a tram 'lifted onto one side' at 40mph in the same area on October 31. BTP said the claim 'will now form one of our lines of inquiry'. And commuter Andy Smith said last summer he wrote to Transport for London to complain after the tram he was travelling on approached the same corner too fast. He said: 'I felt that the train was going to derail because the speed was so fast I didn't think we were going to make the left-hand turn. I knew this was coming.' Survivors of the disaster told how they heard 'crying and screaming' after the carriages hit the ground, pictured The incident occurred near Sandilands tram stop in Croydon, south London, pictured, on a steep bend The Rail Accident Investigation Branch (RAIB) has launched a witness appeal, with anyone who was on the tram or has information relevant to the accident being asked to complete an incident form on the organisation's website. An interim report into what happened will be published by the RAIB next week, with a final report, including any safety recommendations, coming at the conclusion of the investigation. On Friday an extra minute's silence was held to remember the victims during the town's Armistice Day ceremony. Croydon MP Gavin Barwell spoke to relatives near the scene where floral tributes and football scarves have been placed. Authorities are still working on formally identifying the victims, Mr Barwell said. He said: 'It's quite right that the authorities absolutely want to make sure when they give a formal identification that they've got that 100 per cent right. Injured passengers were taken to St George's Hospital in south west London and Croydon University Hospital. Some of the 20 survivors at St George's had limbs amputated. One passenger suffered a collapsed lung. Personal injury expects said claims arising from the tram crash could reach millions of pounds. TRAM PASSENGER CLAIMS CARRIAGE 'LIFTED ONTO ONE SIDE' ON SAME STRETCH OF TRACK LAST WEEK Andy Nias posted this message on Facebook earlier following the fatal Croydon crash. He claimed he was on a tram which 'lifted onto one side' last week on the same stretch of track A passenger on a tram travelling on the same stretch of track last week, told how he was left shaken after he claimed it 'lifted onto one side'. Andy Nias wrote on Facebook that he and 29 fellow travellers feared the worst when their tram 'took the hard corner to Sandilands at 40mph'. He said on October 31: 'Oh mate...30 of us on the tram this morning and we all thought our time was up...tram driver took the hard corner to Sandilands at 40mph!! 'I swear the tram lifted onto one side. Everyone still shaking...it's mad.' Locals have raised concerns about the speeds trams can travel at the corner where the carriages derailed. Pat Rooke, 72, a nearby resident, said 'They (some trams) do come around that corner very fast sometimes, and it is quite a sharp bend.' Sue Patel, who lives near the station, added: 'I heard a noise at around 6 o'clock and I thought maybe it was a car or something. But then I saw there were helicopters.' 'There's quite a big bend. You come through the tunnel and there's quite a sharp bend.' In February 2012 a tram, carrying 100 passengers, also derailed on the line but no one was hurt. The accident happened about half a mile from today's fatal crash.
URL: http://www.dailymail.co.uk/news/article-3929748/Croydon-tram-crash-carriages-carried-away-lorry-police-probe-claims-derailed-just-days-seven-people-died-tragedy.html

  5%|▌         | 5/96 [02:39<48:52, 32.23s/it]

Date: 2016-11-08 14:54:51
Title: People are pissed over Toblerone's new candy size
Description: It's a triangle offense.



Toblerone is facing a mountain of criticism from British consumers who are outraged over the bigger spaces between the distinctive peaks in the chocolate bar.



The product's maker, US-based Mondelez International, attributes the revolt to an effort to reduce the weight of what were 400-gram and 170-gram bars.



"Like many other companies, we are experiencing higher costs for numerous ingredients," Toblerone said on its Facebook page.



"We carry these costs for as long as possible, but to ensure Toblerone remains on-shelf, is affordable and retains the triangular shape, we have had to reduce the weight of just two of our bars in the UK, from the wider range of available Toblerone products," it said.



As a result, the two bars have been reduced in weight to 360 grams and 150 grams - but the packaging size has remained the same.



But consumers were bent out of shape and roundly panned the move.



"Fair enough reducing the weight of the bar, but why the big gap in between segments? Looks stupid imo [in my opinion], could have just made the bar shorter and kept the original design," Lee Yarker wrote.



Stephen Mason noted that "Toblerone is all about the triangle."



"Why couldn't you just lose a triangle at the end or make the triangles smaller? I'm afraid that this is going the way of Cadbury Creme Egg and off my seasonal treat list as I will forever be disappointed," he wrote.



And Nicholas Barker asked why not just raise the price?



"It's not as if people eat Toblerone everyday. You could literally double the price and people would still buy it. Fools," he ranted.



Other food companies have announced price hikes because of the falling value of the British pound after Brexit - the UK's decision to leave the European Union.



A spokeswoman for Toblerone - which was originally created in Switzerland -- acknowledged that the foreign exchange rate was unfavorable, but insisted that "this change wasn't done as a result of Brexit," the BBC reported.
Text: It's a triangle offense. Toblerone is facing a mountain of criticism from British consumers who are outraged over the bigger spaces between the distinctive peaks in the chocolate bar. The product's maker, US-based Mondelez International, attributes the revolt to an effort to reduce the weight of what were 400-gram and 170-gram bars. "Like many other companies, we are experiencing higher costs for numerous ingredients," Toblerone said on its Facebook page. "We carry these costs for as long as possible, but to ensure Toblerone remains on-shelf, is affordable and retains the triangular shape, we have had to reduce the weight of just two of our bars in the UK, from the wider range of available Toblerone products," it said. As a result, the two bars have been reduced in weight to 360 grams and 150 grams - but the packaging size has remained the same. But consumers were bent out of shape and roundly panned the move. "Fair enough reducing the weight of the bar, but why the big gap in between segments? Looks stupid imo [in my opinion], could have just made the bar shorter and kept the original design," Lee Yarker wrote. Stephen Mason noted that "Toblerone is all about the triangle." "Why couldn't you just lose a triangle at the end or make the triangles smaller? I'm afraid that this is going the way of Cadbury Creme Egg and off my seasonal treat list as I will forever be disappointed," he wrote. And Nicholas Barker asked why not just raise the price? "It's not as if people eat Toblerone everyday. You could literally double the price and people would still buy it. Fools," he ranted. Other food companies have announced price hikes because of the falling value of the British pound after Brexit - the UK's decision to leave the European Union. A spokeswoman for Toblerone - which was originally created in Switzerland -- acknowledged that the foreign exchange rate was unfavorable, but insisted that "this change wasn't done as a result of Brexit," the BBC reported.
URL: http://nypost.com/2016/11/08/people-are-pissed-over-toblerones-new-candy-size/

  6%|▋         | 6/96 [03:04<44:30, 29.67s/it]

Date: 2016-11-03 05:43:48
Title: Sports world reacts to the Cubs' World Series win
Description: So much shock. So much joy.
Text: Chicago Cubs players celebrate on the field after defeating the Cleveland Indians in game seven of the 2016 World Series at Progressive Field. (Photo: Ken Blaze-USA TODAY Sports) The Chicago Cubs are World Series champions. That's a sentence that not many expected to be able to accurately write. But on Wednesday, it happened. The Cubs edged out the Indians 8-7 in 10 innings to take Game 7 and win their first World Series since 1908. Now, 108 years means a lot of excitement. This was how the sports world reacted. World Series Champions. #FlyTheWhttps://t.co/1E3dXohSkI- Chicago Cubs (@Cubs) November 03, 2016 Kris Bryant smiling as he fields and throws for the final out is the greatest. pic.twitter.com/8bAU1ayKbJ -- Mike Cole (@MikeColeNESN) November 3, 2016 12:47 a.m. Nov. 3, 2016. The end of 108 years of heartbreak on the North Side of Chicago. The ghosts & the goats can go home now. -- Jayson Stark (@jaysonst) November 3, 2016 Congratulations to the 2016 Chicago Cubs...once in a lifetime...or two lifetimes. -- Michael Wilbon (@RealMikeWilbon) November 3, 2016 Steve Bartman needs to go streaking down Waveland Ave in just his headphones tonight. -- Brett Anderson (@BrettAnderson35) November 3, 2016 Knew it would feel amazing if it happened. Didn't think I'd be sobbing like a goddamn child. Truly thought I'd never see this. What a ride. -- Mark Titus (@clubtrillion) November 3, 2016 For the first time ever, the Wrigley Field marquee reads: "World Series Champions." pic.twitter.com/fWfJSLRueE -- SportsCenter (@SportsCenter) November 3, 2016 Great way to end the baseball season...congrats to the cubbies...city of Chicago is the place to be tonight -- Christian Yelich (@ChristianYelich) November 3, 2016 Zobrist has gotta be pumped he can finally get rid of that Saturn -- Phil Hughes (@PJHughes45) November 3, 2016 genie, you're free pic.twitter.com/XtsIdBita0 -- Freddie Campion (@FreddieCampion) November 3, 2016 Plane taking off. Let's go Cubbies!!!! -- DWade (@DwyaneWade) November 3, 2016 Every curse has its moment when it must end, or when at the very least adult rational sportscasters must stop acting like curses exist. -- Linda Holmes (@nprmonkeysee) November 3, 2016 Pretty good stuff. pic.twitter.com/i9ptNUJpbs -- Johnny Kane (@JohnnyKaneFSD) November 3, 2016 I want Steve Bartman to throw out the first pitch for Cubs Opening Day in 2017. -- Richard Deitsch (@richarddeitsch) November 3, 2016 Congrats to the newest World Champions, the Chicago @Cubs, from the Kansas City Royals! pic.twitter.com/X8ox2wMl8H -- Kansas City Royals (@Royals) November 3, 2016 "Kyrie not gone save y'all this time" pic.twitter.com/rkkgeaAmVI -- Papi (@Kxngsosa) November 3, 2016 This is a great great sight pic.twitter.com/nMeCRC0600 -- Steve DiMeglio (@Steve_DiMeglio) November 3, 2016 Steve Bartman, all is forgiven. -- David Burge (@iowahawkblog) November 3, 2016 This is surreal. Thousands of Cubs fans singing "Go Cubs Go" in someone else's ballpark 300 miles from Wrigley. -- Jayson Stark (@jaysonst) November 3, 2016 Bill Murray just achieved total consciousness. -- Don Jozwiak (@djoz) November 3, 2016 This guy deserves a ring. #WorldSeriespic.twitter.com/bR459CqQwE -- Austin Hunt (@AustinHunt) November 3, 2016 Read or Share this story: http://usat.ly/2fgYabD
URL: http://www.usatoday.com/story/sports/ftw/2016/11/03/sports-world-reacts-to-the-chicago-cubs-winning-their-first-world-series-since-1908/93225730/

  7%|▋         | 7/96 [03:23<38:55, 26.25s/it]

Date: 2016-11-10 23:18:47
Title: Donald Trump and Barack Obama meet at White House
Description: President Barack Obama describes White House transition talks with Donald Trump as "excellent".
Text: Media caption Trump and Obama play nice, but it wasn't always so US President-elect Donald Trump has said it was a "great honour" to meet President Barack Obama for transition talks at the White House. Mr Obama said he was "encouraged" by their "excellent" and "wide-ranging" conversation, lasting over an hour. During the election campaign, Mr Trump vowed to dismantle Mr Obama's legacy and he has previously questioned his US citizenship. Mr Obama, meanwhile, had called Mr Trump "uniquely unqualified". But following Mr Trump's shock defeat of Hillary Clinton in Tuesday's election, Mr Obama appealed for national unity and said he was "rooting" for him. After Thursday's behind-closed-doors meeting in the White House, Mr Obama said: "My number one priority in the coming two months is to try to facilitate a transition that ensures our president-elect is successful." Image copyright AP Image caption President Barack Obama meets with President-elect Donald Trump in the Oval Office He said they had discussed domestic and foreign policy and he had been "very encouraged" by Mr Trump's interest in working with President Obama's team on issues facing the US. Mr Trump said he would "very much look forward" to dealing with President Obama in future. "I have great respect, the meeting lasted for almost an hour and a half, and it could've, as far as I'm concerned, it could've gone on for a lot longer," the president-elect said. "We discussed a lot of different situations - some wonderful and some difficulties." Image copyright White House Image caption Melania Trump and Michelle Obama in conversation White House spokesman Josh Earnest said the two men did not resolve their differences but "the meeting might have been at least a little less awkward than some might have expected". "President Obama came away from the meeting with renewed confidence in the commitment of the president-elect to engage in an effective, smooth transition," he said. Mr Trump flew from New York on his private jet and landed at Reagan National Airport, just outside the nation's capital. The president-elect was accompanied by his wife, Melania, who had a meeting with First Lady Michelle Obama. Image copyright European Press Agency He, along with Vice-President-elect Mike Pence, then met Republican House Speaker Paul Ryan, saying they "can't get started fast enough, whether it's healthcare or immigration". Mr Ryan described it as a "fantastic, productive meeting". President Obama congratulated his successor in a phone call in the early hours of Wednesday. The defeated Mrs Clinton also told supporters Mr Trump had to be given a "chance to lead". Despite appeals for unity, thousands took to the streets of major US cities on Wednesday. Many chanted: "Not my president." Sixty-five people were arrested in New York, while shop windows were smashed and missiles hurled at riot police during demonstrations in Oakland, California. In Chicago, crowds blocked the entrance to Trump Tower, chanting: "No Trump, No KKK, No Fascists USA", and a mass anti-Trump rally shut down the key 101 freeway in Los Angeles. Media caption Trump meets highest ranking Republican Mr Obama and Mr Trump have a history of mutual hostility. Mr Trump led the charge in challenging the legitimacy of Mr Obama's presidency through the "birther" movement, which falsely claimed the Hawaii-born commander-in-chief was actually born outside the US. The businessman also called Mr Obama "the worst president in the history of the United States". For his part, the president famously skewered Mr Trump in person at the 2011 White House Correspondents' Association Dinner, which some have suggested may have spurred the New York billionaire to seek revenge. Analysis Image copyright AP By Anthony Zurcher, BBC North America reporter Donald Trump launched himself onto the national political stage by questioning Barack Obama's US citizenship and eligibility to be president. Mr Obama spent the last few months of the 2016 presidential election assailing Mr Trump's fitness to occupy the nation's highest office. Now they've met for the first time ever - as president and president-elect. Talk about awkward. Although both candidates played nice in their Oval Office get-together, there's no denying that the two men present a clear contrast in manner and style. In the past, the American public has displayed a tendency to seek qualities in their next president that the current occupant of the Oval Office is perceived to lack. Contrast George W Bush's board-room manner with Bill Clinton's improvisational chaos or Jimmy Carter's squeaky clean reputation after Richard Nixon's Machiavellian manoeuvres. In this case, they have opted for Mr Trump's blunt talk and bombast after Mr Obama's detached professorial coolness. Although it wasn't on display this morning in the White House, Inauguration Day could provide a severe case of presidential personality whiplash. With the Republicans now holding a majority in both chambers of the US Congress, Mr Trump can more easily target key Obama initiatives like such as his healthcare reforms. Mr Trump is already setting up bilaterals ahead of his January inauguration as the nation's 45th US president. The office of British Prime Minister Theresa May said on Thursday that the president-elect had invited her in a phone call to visit him "as soon as possible". Media caption In cities across the US, protesters took to the streets with chants and banners Ms May's office said in a statement that Mr Trump had praised the trans-Atlantic "special relationship" while discussing his "close and personal connections" with the UK. Mr Trump has family and business ties to Scotland. The president-elect's transition team for the 10-week period until inauguration will be led by Chris Christie, Governor of New Jersey. Mr Trump, who has never held elected office, has said his immediate priorities will be restoring the country's infrastructure and doubling its economic growth. How Donald Trump won the presidency Democrat Republican Other Undeclared Your browser does not support this interactive content. You must be using a modern browser with Javascript enabled to view our results maps. As president-elect, he is entitled to get the same daily intelligence briefing as President Obama, which includes information on covert US operations and other data gathered by America's 17 intelligence agencies. Mr Trump's team is understood to be focused on quickly filling key national security posts. It is not yet clear who will sit his cabinet or fill senior posts in his administration, such as chief of staff, but several figures in his inner circle have been mentioned.
URL: http://www.bbc.com/news/election-us-2016-37932231

  8%|▊         | 8/96 [03:47<37:02, 25.25s/it]

Date: 2016-11-10 03:37:19
Title: Trump protest march in Seattle marred by shooting
Description: The shooting didn't seem to be related to the anti-Trump demonstrations but stemmed from 'some type of personal argument', Seattle police assistant chief Robert Merner said.
Text: A gunman opened fire in downtown Seattle on Wednesday night following an argument and wounded five people not far from protests over the surprise victory of Republican Donald Trump in the U.S. presidential election. The shooting did not appear to be related to the anti-Trump demonstrations but instead stemmed from 'some type of personal argument', Robert Merner, assistant chief of the Seattle Police Department, told reporters. 'It appears that some type of argument took place. This individual began to walk away from the crowd, then turned and fired into the crowd,' Merner said. He said the suspect then fled from the area on foot and remained at large. A gunman opened fire in downtown Seattle on Wednesday night following an argument and wounded five people not far from protests over the surprise victory of Republican Donald Trump Medics respond to a multiple victim shooting near Third Avenue and Pike Street in Seattle The shooting did not appear to be related to the anti-Trump demonstrations but instead stemmed from 'some type of personal argument', Robert Merner, assistant chief of the Seattle Police Department, said Police and fire crews were on the scene in less than a minute because they had been in the area to monitor the demonstrations, he said, but did not arrive in time to engage the suspect. Police closed down the intersection of Third Avenue and Pine streets, where the shooting took place in front of a 7-11 convenience store. 7-11 manager Sharon Keith told reporters she heard what sounded like firecrackers and told everyone to get down. Keith says she was inside the store Wednesday evening and could see multiple people on the ground outside afterward. 'How do you describe that, there were multiple people down, a lot of blood,' she said. Authorities say a man escaped on foot after firing into a crowd and wounding five people outside a convenience store Sharon Keith, center-left, who works at the 7-11 near where the shooting occurred, cries as she talks to reporters about the shooting Harborview Medical Center spokeswoman Susan Gregg says the condition of several people wounded by gunfire in downtown Seattle has improved from serious to satisfactory condition. Gregg says one woman and two men shot when a gunman opened fire Wednesday evening were improving at the hospital Wednesday night. She says two other men remain in critical, but stable condition in intensive care. The five victims range in age from 20s to 50s and sustained injuries to their legs, chest and neck. Police were still searching for a male gunman. Police watch as people gather in protest to the election of Republican Donald Trump Seattle (pictured) was just one of many cities across the country where protests were staged
URL: http://www.dailymail.co.uk/news/article-3922446/Report-shooting-multiple-victims-near-Trump-protest-Seattle-PD.html

  9%|▉         | 9/96 [04:07<34:14, 23.61s/it]

Date: 2016-11-08 23:45:35
Title: Hillary Clinton in the clear as FBI announces it has not changed mind on charges
Description: Hillary Clinton received an unexpected boost to her campaign with just hours left before the US presidential election as the FBI announced on Sunday night that it had found no evidence of criminal wrongdoing in her use of a private email server.
Text: Hillary Clinton received an unexpected boost to her campaign with just hours left before the US presidential election as the FBI announced on Sunday night that it had found no evidence of criminal wrongdoing in her use of a private email server. James Comey, the FBI director, took the nation by surprise when he released a second letter in which he said the FBI had not changed its conclusions from its first report on Mrs Clinton in July. The announcement, made as Americans prepared to go to the polls on Tuesday, lifted a shadow left hanging over the Democrat candidate. It followed a surge of support from Hispanic voters in the latest polls.
URL: http://www.telegraph.co.uk/news/2016/11/06/us-election-hillary-clinton-up-in-polls-as-hispanic-surge-threat/

 10%|█         | 10/96 [04:21<29:58, 20.91s/it]

Date: 2016-11-03 05:10:42
Title: Chicago Cubs win World Series for first time in 108 years in dramatic 10th innings showdown
Description: The Cubs won 8-7 in an extra innings delayed by rain as thousands gathered outside Wrigley Field
Text: Get daily updates directly to your inbox + Subscribe Thank you for subscribing! Could not subscribe, try again later Invalid Email The Chicago Cubs beat the Cleveland Indians to win their first World Series in 108 years. The Cubs won 8-7 after the deciding game needed an extra innings which was delayed for rain and ended at almost midnight on Wednesday. The dramatic victory brought an end to the longest title drought in North American professional sports. The triumph of Chicago's beloved Cubbies set off a wild celebration in the streets of the Windy City after more than a century of pent up frustration for fans since their last Major League Baseball championship in 1908. MVP Zobrist, who helped the Kansas City Royals to the championship last year, said at the post-match presentation shown on BT Sport 1: "It's unbelievable. I can't even put it into words. It's an unbelievable team to be a part of. "Every guy on this team roots for each other, takes care of each other and picks each other up and that's what we did during that rain delay." Rizzo added: "It's the best game I've ever been a part of. What a team. We started this year as heavy favourites and we went wire to wire all year as the best team in baseball. "The Indians did one heck of a job but this is the best feeling in the world. "We're world champions. For the rest of our lives." (Photo: Tommy Gilligan-USA TODAY Sports) (Photo: Getty) (Photo: Getty) And no one was celebrating harder it seemed, than US presidential candidate Hillary Clinton. The diehard Cubs fan was pictured shouting and with her fists in the air as she watched the thrilling conclusion while out on the campaign trail. It was an unguarded moment that may cost her - Cleveland is in Ohio, likely to be one of the swing states in the upcoming election - but clearly she didn't care. With the win, the Cubs clinched the best-of-seven series in seven games after the Indians squandered a 3-1 lead. The Cleveland team fell one victory short of their first Major League Baseball title in 68 years. The Cubs, who had not won baseball's biggest prize since 1908, had seen a 6-3 lead evaporate in the eighth inning but, after RBIs from Ben Zobrist and Miguel Montero, Mike Montgomery gained the final out in the 10th to secure an 8-7 victory. It was the fourth World Series decider to go to an extra innings and the first since 1997, when the Indians were beaten by the Florida Marlins. The Cubs, who had not even reached a World Series since 1945, are the first team to overturn a 3-1 deficit since 1985.
URL: http://www.mirror.co.uk/sport/other-sports/american-sports/chicago-cubs-win-world-series-9185077

 11%|█▏        | 11/96 [04:38<27:36, 19.48s/it]

Date: 2016-11-10 19:44:00
Title: Explosion and gunfire outside German consulate in Afghanistan
Description: AN EXPLOSION outside the German consulate in the city of Mazar-i-Sharif in northern Afghanistan has killed two people.
Text: Explosion and gunfire reported outside German consulate in Afghanistan The blast was followed by gunfire according to reports on the ground. A car laden with explosives apparently initiated the attack at the compound's security wall, followed by gunfire and an explosion inside the hotel. There have been at least two fatalities and 84 people have been taken to hospital. The attack happened at around 11:30pm local time, close to the consulate and a hotel as well as several guesthouses.
URL: http://www.express.co.uk/news/world/731052/German-consulate-explosion-gunfire-Afghanistan

 11%|█▏        | 11/96 [04:53<37:49, 26.70s/it]

KeyboardInterrupt:

In [28]:
df = pd.DataFrame(data_list)
df.to_excel('news_5w1h_llama3.xlsx', index=False)
df.to_csv('news_5w1h_llama3.csv', index=False, encoding='utf-8')

In [29]:
df

,text,what_true,where_true,when_true,who_true,why_true,how_true,what_pred,where_pred,when_pred,who_pred,why_pred,how_pred
0,FBI Director James B. Comey. (MICHAEL REYNOLDS...,Clinton's emails,,Sunday,James B. Comey; Clinton,the new email cache may have nothing of releva...,vague note,The FBI's review of new emails related to Hill...,USA (specifically Pennsylvania and Ohio),Sunday (2016-11-06),"FBI Director James B. Comey, Hillary Clinton, ...",Not mentioned,"The FBI reviewed the material quickly, suggest..."
1,After the defeat Hillary superfan Katy Perry s...,protest outside Trump Tower after US election ...,New York City,the early hours of Wednesday,Lady Gaga; Katy Perry; Demi Lovato,Donald Trump emerged victorious,stages protest,Celebrities stage a protest and express their ...,"Trump Tower, New York City",2016-11-09,"Lady Gaga, Katy Perry, Demi Lovato, Eva Longor...",The reason behind the event is not explicitly ...,The protest was staged outside Trump Tower in ...
2,Her campaign said the seemingly positive outco...,Blames F.B.I. Director for Election Loss,Saturday,,Hillary Clinton,he had revived the inquiry into her use of a p...,Blames,Hillary Clinton blaming F.B.I. Director James ...,United States (battleground states),2016-11-12,"Hillary Clinton, James B. Comey",The announcement by James B. Comey that he had...,The F.B.I.'s examination of new emails and Mr....
3,The death toll from a powerful Taliban truck b...,attacks German consulate; truck bombing,northern Afghan city of Mazar-i-Sharif,late Thursday,Taliban,revenge attack,rammed his explosives-laden; rammed,Truck bombing at the German consulate in Mazar...,"Mazar-i-Sharif city, northern Afghanistan",Thursday (late) and Friday (at least six death...,Taliban,Revenge attack for US air strikes in Kunduz pr...,A suicide attacker rammed his explosives-laden...
4,Police investigating the Croydon tram crash ha...,name final three victims; died,Croydon,Wednesday,"Donald Collett, Philip Logan and Robert Huxley...",above the permitted speed; tram crash that kil...,high speed; crash,Croydon tram crash that killed seven people,"Sandilands tram stop in Croydon, south London","Wednesday (no specific date mentioned), but th...","Police, tram driver, passengers, and victims i...","Not mentioned explicitly, but the investigatio...",The tram overturned as it entered a bend at hi...
5,It's a triangle offense. Toblerone is facing a...,are pissed,UK,,Toblerone; People,higher costs for numerous ingredients; new can...,criticism; facing,Toblerone's decision to reduce the weight of t...,UK,2016-11 (exact date not specified),"Toblerone, Mondelez International, British con...",To reduce costs due to higher prices for ingre...,By reducing the weight of two bars from 400-gr...
6,Chicago Cubs players celebrate on the field af...,reacts to the Cubs' World Series win,Progressive Field,"November 03, 2016",Sports world; Chicago Cubs,Chicago Cubs are World Series champions; World...,innings; 8-7 in 10 innings,The Chicago Cubs won the World Series for the ...,"Progressive Field in Cleveland, Ohio","November 3, 2016","Chicago Cubs, Cleveland Indians, various sport...",Not mentioned,The Cubs edged out the Indians 8-7 in 10 innings
7,"Media caption Trump and Obama play nice, but i...",meet at White House,White House,Thursday,Donald Trump; Barack Obama,transition talks,,Transition talks between President-elect Donal...,"The White House, Washington D.C.","Thursday, after Trump's shock defeat of Hillar...",Donald Trump and Barack Obama,To facilitate a smooth transition and ensure T...,They had an 'excellent' and 'wide-ranging' con...
8,A gunman opened fire in downtown Seattle on We...,opened fire; Trump protest march in Seattle ma...,downtown Seattle,Wednesday night,A gunman,some type of personal argument,near; fire,"A shooting occurred in downtown Seattle, wound...","Downtown Seattle, near Third Avenue and Pine s...",Wednesday night (no specific date mentioned),"A gunman, Seattle police assistant chief Rober...",The shooting stemmed from 'some type of person...,A gunman opened fire into a crowd after an arg...
9,Hillary Clinton received an unexpected boost t...,no evidence of criminal wrongdoing in her use ...,,hours left before the US presidential election...,Hillary Clinton; FBI,,found no evidence,FBI announcement on Hillary Clinton's use of a...,US presidential election,Sunday night (2016-11-06),"Hillary Clinton, James Comey",Not mentioned,Release of a second letter by FBI director Jam...
10,Get daily updates directly to your inbox + Sub...,win World Series,Wrigley Field,almost midnight on Wednesday,Chicago Cubs,beat the Cleveland Indians; We're world champions,extra innings which was delayed; beat the Clev...,Won the World Series for the first time in 108...,"Wrigley Field, Chicago",2016-11-03,Chicago Cubs,To end their longest title drought in North Am...,In a dramatic 10th innings showdown after a ra...

In [30]:
# gets articles and their extracted components from the spreadsheets and compares extracted components with the true (annotated) components
df = pd.read_excel("news_5w1h_llama3.xlsx")
df = df.fillna("")
data_list2 = df.to_dict(orient="records")
e = evaluate(data_list2)
df_e = pd.DataFrame(e)
df_e['model'] = 'llama3.1'
df_e.to_pickle("news_5w1h_llama3_avaliacao.pkl")

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Warning: Empty reference sentence detected; setting raw BERTScores to 0.

tensor([0.8481, 0.0000, 0.8416, 0.9200, 0.8130, 0.7999])
System level F1 score: 0.704

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

tensor([0.8655, 0.9060, 0.7527, 0.9257, 0.8514, 0.8681])
System level F1 score: 0.862

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Warning: Empty reference sentence detected; setting raw BERTScores to 0.

tensor([0.9289, 0.8135, 0.0000, 0.8939, 0.9045, 0.7712])
System level F1 score: 0.719

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

tensor([0.8664, 0.8868, 0.8494, 1.0000, 0.8525, 0.8617])
System level F1 score: 0.886

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

tensor([0.8247, 0.8455, 0.8298, 0.8617, 0.8381, 0.8740])
System level F1 score: 0.846

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Warning: Empty reference sentence detected; setting raw BERTScores to 0.

tensor([0.8153, 1.0000, 0.0000, 0.8856, 0.8706, 0.8045])
System level F1 score: 0.729

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

tensor([0.9030, 0.8780, 0.9828, 0.8643, 0.8028, 0.9081])
System level F1 score: 0.890

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Warning: Empty reference sentence detected; setting raw BERTScores to 0.

tensor([0.8927, 0.8820, 0.8172, 0.9694, 0.8494, 0.0000])
System level F1 score: 0.735

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

tensor([0.8989, 0.8626, 0.9134, 0.8821, 0.8555, 0.8333])
System level F1 score: 0.874

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Warning: Empty reference sentence detected; setting raw BERTScores to 0.

tensor([0.9201, 0.0000, 0.8378, 0.9216, 0.0000, 0.8077])
System level F1 score: 0.581

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

tensor([0.8743, 0.9569, 0.7788, 1.0000, 0.8370, 0.8676])
System level F1 score: 0.886

In [31]:
df_e

,0,1,2,3,4,5,model
0,{'text': 'FBI Director James B. Comey. (MICHAE...,[The FBI's review of new emails related to Hil...,"[Clinton's emails, , Sunday, James B. Comey; C...","[tensor(0.8191), tensor(0.), tensor(0.7678), t...","[tensor(0.8792), tensor(0.), tensor(0.9312), t...","[tensor(0.8481), tensor(0.), tensor(0.8416), t...",llama3.1
1,{'text': 'After the defeat Hillary superfan Ka...,[Celebrities stage a protest and express their...,[protest outside Trump Tower after US election...,"[tensor(0.8828), tensor(0.8831), tensor(0.7454...","[tensor(0.8488), tensor(0.9301), tensor(0.7601...","[tensor(0.8655), tensor(0.9060), tensor(0.7527...",llama3.1
2,{'text': 'Her campaign said the seemingly posi...,[Hillary Clinton blaming F.B.I. Director James...,"[Blames F.B.I. Director for Election Loss, Sat...","[tensor(0.9174), tensor(0.8038), tensor(0.), t...","[tensor(0.9408), tensor(0.8234), tensor(0.), t...","[tensor(0.9289), tensor(0.8135), tensor(0.), t...",llama3.1
3,{'text': 'The death toll from a powerful Talib...,[Truck bombing at the German consulate in Maza...,"[attacks German consulate; truck bombing, nort...","[tensor(0.8326), tensor(0.8790), tensor(0.8234...","[tensor(0.9030), tensor(0.8948), tensor(0.8771...","[tensor(0.8664), tensor(0.8868), tensor(0.8494...",llama3.1
4,{'text': 'Police investigating the Croydon tra...,"[Croydon tram crash that killed seven people, ...","[name final three victims; died, Croydon, Wedn...","[tensor(0.8111), tensor(0.8085), tensor(0.7926...","[tensor(0.8386), tensor(0.8860), tensor(0.8705...","[tensor(0.8247), tensor(0.8455), tensor(0.8298...",llama3.1
5,{'text': 'It's a triangle offense. Toblerone i...,[Toblerone's decision to reduce the weight of ...,"[are pissed, UK, , Toblerone; People, higher c...","[tensor(0.7917), tensor(1.0000), tensor(0.), t...","[tensor(0.8403), tensor(1.0000), tensor(0.), t...","[tensor(0.8153), tensor(1.0000), tensor(0.), t...",llama3.1
6,{'text': 'Chicago Cubs players celebrate on th...,[The Chicago Cubs won the World Series for the...,"[reacts to the Cubs' World Series win, Progres...","[tensor(0.8810), tensor(0.8385), tensor(0.9828...","[tensor(0.9262), tensor(0.9213), tensor(0.9828...","[tensor(0.9030), tensor(0.8780), tensor(0.9828...",llama3.1
7,{'text': 'Media caption Trump and Obama play n...,[Transition talks between President-elect Dona...,"[meet at White House, White House, Thursday, D...","[tensor(0.8576), tensor(0.8540), tensor(0.7863...","[tensor(0.9309), tensor(0.9119), tensor(0.8506...","[tensor(0.8927), tensor(0.8820), tensor(0.8172...",llama3.1
8,{'text': 'A gunman opened fire in downtown Sea...,"[A shooting occurred in downtown Seattle, woun...",[opened fire; Trump protest march in Seattle m...,"[tensor(0.8986), tensor(0.7922), tensor(0.8626...","[tensor(0.8992), tensor(0.9467), tensor(0.9705...","[tensor(0.8989), tensor(0.8626), tensor(0.9134...",llama3.1
9,{'text': 'Hillary Clinton received an unexpect...,[FBI announcement on Hillary Clinton's use of ...,[no evidence of criminal wrongdoing in her use...,"[tensor(0.9272), tensor(0.), tensor(0.8269), t...","[tensor(0.9131), tensor(0.), tensor(0.8490), t...","[tensor(0.9201), tensor(0.), tensor(0.8378), t...",llama3.1
10,{'text': 'Get daily updates directly to your i...,[Won the World Series for the first time in 10...,"[win World Series, Wrigley Field, almost midni...","[tensor(0.8224), tensor(0.9374), tensor(0.7472...","[tensor(0.9331), tensor(0.9772), tensor(0.8131...","[tensor(0.8743), tensor(0.9569), tensor(0.7788...",llama3.1